pos(f(acab,abcc)).
pos(f(adietermann,akonstanzebreitebner)).
pos(f(aleilanisarelle,bcba)).
pos(f(abillyconnolly,asheilapaterson)).
pos(f(alorigalinski,ageorgeclooney)).
pos(f(apaolaciampi,bbba)).
pos(f(aangelinasarova,asavahashamov)).
pos(f(amaurolenares,aaca)).
pos(f(asharonstone,adanielvonbargen)).
pos(f(baab,aconsuelolupo)).
pos(f(acbb,caca)).
pos(f(adanielvonbargen,aleilanisarelle)).
pos(f(azensmichael,ajrggudzuhn)).
pos(f(aaltmanroberti,afredward)).
pos(f(asalvatorelazzaro,afrancomirabella)).
pos(f(averhoevenpauli,adanielvonbargen)).
pos(f(avincentlecoeur,aabc)).
pos(f(ametcalfestephen,anormanarmour)).
pos(f(asharonstone,ajaimzwoolvett)).
pos(f(ajeannetripplehorn,adenisarndt)).
pos(f(asamantharnier,aguillaumeromain)).
pos(f(aannamariagherardi,amanliosgalambro)).
pos(f(asamantharnier,apierrearditi)).
pos(f(ahughdancy,afloramontgomery)).
pos(f(bbba,abab)).
pos(f(acorradofortuna,aradarassimov)).
pos(f(apieradegliesposti,asaromiano)).
pos(f(aandreasschwaiger,ccac)).
pos(f(caac,aacb)).
pos(f(anevenakokanova,akostatsonev)).
pos(f(athomasstielner,ccbb)).
pos(f(amarcoleonardi,acba)).
pos(f(ametcalfestephen,agilbellows)).
pos(f(acatonjonesmichael,aaba)).
pos(f(aacb,amaurizionicolosi)).
pos(f(acbc,alaurabetti)).
pos(f(baaa,cbca)).
pos(f(atzenokandov,acab)).
pos(f(cccc,anormanarmour)).
pos(f(baba,astevekalfa)).
pos(f(adenisarndt,ajeannetripplehorn)).
pos(f(bcbc,bbbc)).
pos(f(adenisarndt,asharonstone)).
pos(f(aalicjajachiewicz,asotirmaynolovski)).
pos(f(apaullnolan,abaa)).
pos(f(adidierdijoux,aarmelledeutsch)).
pos(f(cbbb,ajustinmonjo)).
pos(f(acarolflorence,abradpitt)).
pos(f(cbaa,amarkusbker)).
pos(f(acbc,abab)).
pos(f(baba,bcbc)).
pos(f(asoderberghsteven,anelsonpeltz)).
pos(f(apakulaalanj,aanthonyheald)).
pos(f(acorradofortuna,atizianalodato)).
pos(f(abraunbettinai,ahorstkummeth)).
pos(f(akrgnther,ahubertmulzer)).
pos(f(aceceliaannbirt,abradpitt)).
pos(f(bcba,asharonstone)).
pos(f(amiguelferrer,adebraengle)).
pos(f(araffaeladavi,babc)).
pos(f(adavidarnett,bcaa)).
pos(f(ageorgeclooney,aminianden)).
pos(f(apatricejuiff,asamantharnier)).
pos(f(cbbb,agusmercurio)).
pos(f(aaac,acatherinezetajones)).
pos(f(abillcable,asharonstone)).
pos(f(accilecassel,bcbc)).
pos(f(ajorgerhernandez,acbb)).
pos(f(abrigittefossey,bbaa)).
pos(f(arenateschroeter,bccb)).
pos(f(ascottcaan,cabc)).
pos(f(abca,ametcalfestephen)).
pos(f(abradpitt,afrankpatton)).
pos(f(aandreasschwaiger,aclaudiamessner)).
pos(f(aaca,amarcospicuglia)).
pos(f(ageorgedzundza,adorothymalone)).
pos(f(agerdlohmeyer,cbaa)).
pos(f(amarcoleonardi,aeddasabatini)).
pos(f(aluciasardo,agiancarloscuderi)).
pos(f(aaltmanroberti,bbbb)).
pos(f(bcac,araffaeladavi)).
pos(f(amaurolenares,aacb)).
pos(f(apierrearditi,aalexandrawinisky)).
pos(f(adontiffany,adinaconnolly)).
pos(f(cccc,aconnorwiddows)).
pos(f(apunchevborislav,ajannowicki)).
pos(f(abba,aalancpeterson)).
pos(f(alloydalan,arobyndouglass)).
pos(f(aangelahall,asydneypollack)).
pos(f(awayneknight,asharonstone)).
pos(f(aconnorwiddows,bbca)).
pos(f(aapprederisfranck,bbaa)).
pos(f(baac,akrgnther)).
pos(f(abba,anormanarmour)).
pos(f(amichaeldouglas,achelcieross)).
pos(f(afrankcturner,asheilapaterson)).
pos(f(aconnorwiddows,abba)).
pos(f(araffaeladavi,baaa)).
pos(f(aarmelledeutsch,caba)).
pos(f(amarcocavicchioli,aacb)).
pos(f(aarmelledeutsch,avincentlecoeur)).
pos(f(cbcc,bbca)).
pos(f(avyarakovacheva,ageorgistamatov)).
pos(f(astefanpetrov,avyarakovacheva)).
pos(f(akronthalerthomas,aandreasschwaiger)).
pos(f(cccb,aannamariagherardi)).
pos(f(aleahayres,atimrobbins)).
pos(f(cbab,aianholm)).
pos(f(ascottcaan,aannejacques)).
pos(f(afrankpatton,bcab)).
pos(f(ccaa,astoychomazgalov)).
pos(f(caba,asamantharnier)).
pos(f(adinamerrill,avincentdonofrio)).
pos(f(abattiatofranco,aantoninobruschetta)).
pos(f(anevenakokanova,aivangrigorov)).
pos(f(anormanarmour,asheilapaterson)).
pos(f(aleahayres,abrionjames)).
pos(f(afabiolobello,afrancomirabella)).
pos(f(alucavitrano,aannamariagherardi)).
pos(f(caba,baca)).
pos(f(abiagiobarone,amanueladolcemascolo)).
pos(f(abrnicebejo,apatricejuiff)).
pos(f(cbcc,cbab)).
pos(f(anevenakokanova,bcbb)).
pos(f(adietermann,ccac)).
pos(f(asharonstone,alloydalan)).
pos(f(adavidsontag,aannejacques)).
pos(f(baab,acarmelogalati)).
pos(f(asharonstone,adavidmorrissey)).
pos(f(aalancpeterson,asharonstone)).
pos(f(aarmelledeutsch,bccc)).
pos(f(caca,bacc)).
pos(f(adillonmoen,asheilapaterson)).
pos(f(adavidmorrissey,acharlotterampling)).
pos(f(aalicjajachiewicz,acaa)).
pos(f(alaurabetti,acesareapolito)).
pos(f(ajustinmonjo,acaitlinoheaney)).
pos(f(caab,adinamerrill)).
pos(f(agilbellows,asheilapaterson)).
pos(f(aianholm,asharonstone)).
pos(f(asharonstone,ajustinmonjo)).
pos(f(abrigittefossey,adidierdijoux)).
pos(f(anormanarmour,asharonstone)).
pos(f(baab,accc)).
pos(f(anicolegrimaudo,amanliosgalambro)).
pos(f(asaromiano,aluciasardo)).
pos(f(ajurneesmollett,agilbellows)).
pos(f(ascottcaan,aelliottgould)).
pos(f(adimitarhadzhiyanev,asonyadjulgerova)).
pos(f(baac,agutjahrrainer)).
pos(f(aivantonev,aangelinasarova)).
pos(f(aluciasardo,aaab)).
pos(f(asharonstone,ageorgedzundza)).
pos(f(bbba,cbca)).
pos(f(asharonstone,aconnorwiddows)).
pos(f(aterenceharvey,ajanchappell)).
pos(f(adietermann,ajuttawachowiak)).
pos(f(bcbc,agustemmanuelii)).
pos(f(bcbc,aladogedominique)).
pos(f(acynthiastevenson,adeanstockwell)).
pos(f(asonyadjulgerova,astefandanailov)).
pos(f(aapprederisfranck,avincentlecoeur)).
pos(f(abenjohnson,abba)).
pos(f(amaurolenares,aluciasardo)).
pos(f(aalexandrawinisky,bbaa)).
pos(f(aguillaumeromain,ajuliedray)).
pos(f(abillyconnolly,cccc)).
pos(f(babb,aellenthomas)).
pos(f(ccca,atimothypaulperez)).
pos(f(aivankondov,ccaa)).
pos(f(agrimaldiaurelioi,aenzodimartino)).
pos(f(acca,abca)).
pos(f(amarinovichanton,aivanbratanov)).
pos(f(asharonstone,abenjaminmouton)).
pos(f(apakulaalanj,ajuliaroberts)).
pos(f(acaseyaffleck,caca)).
pos(f(ajanchappell,aneilmaskell)).
pos(f(apetergallagher,agretascacchi)).
pos(f(bcba,aleilanisarelle)).
pos(f(asamantharnier,apatricejuiff)).
pos(f(bcab,atimothypaulperez)).
pos(f(afabiolobello,aluciasardo)).
pos(f(ccab,bcbc)).
pos(f(baaa,abab)).
pos(f(acesareapolito,araffaeladavi)).
pos(f(ahorstkummeth,cbaa)).
pos(f(aluciasardo,amarcospicuglia)).
pos(f(acarolflorence,abaa)).
pos(f(abattiatofranco,aaab)).
pos(f(acca,agilbellows)).
pos(f(akunkabaeva,bbcb)).
pos(f(aantoninobruschetta,ccbc)).
pos(f(aluciasardo,abbc)).
pos(f(bbca,afrankcturner)).
pos(f(agrimaldiaurelioi,amarcoleonardi)).
pos(f(awhoopigoldberg,aaaa)).
pos(f(achelcieross,abruceayoung)).
pos(f(ageorgeclooney,amarkgantt)).
pos(f(apaullnolan,acbb)).
pos(f(aannejacques,abradpitt)).
pos(f(cbaa,agerdlohmeyer)).
pos(f(astevekalfa,baba)).
pos(f(amiguelferrer,cbbb)).
pos(f(adavidmorrissey,asharonstone)).
pos(f(abcc,acab)).
pos(f(acynthiastevenson,bbbb)).
pos(f(adinamerrill,aaaa)).
pos(f(aginachiarelli,abenjohnson)).
pos(f(cbab,aconnorwiddows)).
pos(f(aandreasschwaiger,amarenschumacher)).
pos(f(abca,ajurneesmollett)).
pos(f(adinamerrill,atimrobbins)).
pos(f(cabb,ajohnfinn)).
pos(f(asharonstone,aindiravarma)).
pos(f(abruceayoung,aleilanisarelle)).
pos(f(apieradegliesposti,agiancarloscuderi)).
pos(f(ajurneesmollett,aabb)).
pos(f(amaurolenares,apieradegliesposti)).
pos(f(aminianden,aedkross)).
pos(f(agrimaldiaurelioi,acesareapolito)).
pos(f(bacc,aceceliaannbirt)).
pos(f(adavidthewlis,asharonstone)).
pos(f(aganchoganchev,amariashopova)).
pos(f(aandreasschwaiger,cbaa)).
pos(f(agretascacchi,alylelovett)).
pos(f(amariashopova,atzvetolyubrakovski)).
pos(f(cbba,aleilanisarelle)).
pos(f(amariashopova,ageorgistamatov)).
pos(f(aheathcotewilliams,asharonstone)).
pos(f(bccc,aabc)).
pos(f(afredward,agretascacchi)).
pos(f(aapprederisfranck,adidierdijoux)).
pos(f(anikoladadov,amariashopova)).
pos(f(cbaa,ahubertmulzer)).
pos(f(alucavitrano,aluciasardo)).
pos(f(aloccorbery,abrigittefossey)).
pos(f(aludwigbriand,baca)).
pos(f(adinaconnolly,cacb)).
pos(f(asharonstone,bcba)).
pos(f(aalicjajachiewicz,bbac)).
pos(f(asurchadzhievstefani,amikhailmikhajlov)).
pos(f(bcab,apaullnolan)).
pos(f(baaa,aauroraquattrocchi)).
pos(f(avyarakovacheva,anikoladadov)).
pos(f(apakulaalanj,adenzelwashington)).
pos(f(astefandanailov,apetyasilyanova)).
pos(f(abrionjames,adinamerrill)).
pos(f(babc,abbb)).
pos(f(agerdlohmeyer,ccbb)).
pos(f(cbba,averhoevenpauli)).
pos(f(bbca,cbcc)).
pos(f(abac,aganchoganchev)).
pos(f(aleilanisarelle,adanielvonbargen)).
pos(f(asharonstone,aabb)).
pos(f(asheilapaterson,aabb)).
pos(f(atheresascholze,aulrichmhe)).
pos(f(acab,aviktordanchenko)).
pos(f(bbca,aianholm)).
pos(f(ajanchappell,aterenceharvey)).
pos(f(aeddiejemison,ascottcaan)).
pos(f(bcac,aauroraquattrocchi)).
pos(f(awhoopigoldberg,abrionjames)).
pos(f(aapprederisfranck,ccba)).
pos(f(aabb,aginachiarelli)).
pos(f(acarolflorence,bacc)).
pos(f(bcbc,accilecassel)).
pos(f(aaaa,awhoopigoldberg)).
pos(f(agilbellows,aginachiarelli)).
pos(f(agilbellows,asharonstone)).
pos(f(cbaa,baac)).
pos(f(avergnejeanpierre,apierrearditi)).
pos(f(astoychomazgalov,apetyasilyanova)).
pos(f(aludwigbriand,aestefanacastro)).
pos(f(anelsonpeltz,cabc)).
pos(f(afranoisechristophe,astevekalfa)).
pos(f(ahorstkummeth,akarinthaler)).
pos(f(abraunbettinai,atommikulla)).
pos(f(aarmelledeutsch,aloccorbery)).
pos(f(bbba,abbb)).
pos(f(cacb,aminianden)).
pos(f(aivandimov,abac)).
pos(f(ascottcaan,aeddiejemison)).
pos(f(agerdlohmeyer,akarinthaler)).
pos(f(acynthiastevenson,atimrobbins)).
pos(f(asalvatorelazzaro,aantoniettacarbonetti)).
pos(f(aminianden,ascottcaan)).
pos(f(ageorgeclooney,ajorgerhernandez)).
pos(f(avyarakovacheva,atzvetolyubrakovski)).
pos(f(abaa,atimothypaulperez)).
pos(f(abaa,aberniemac)).
pos(f(abillcable,achelcieross)).
pos(f(aivandimov,aangelinasarova)).
pos(f(bbcc,cabb)).
pos(f(agabrieleferzetti,amanliosgalambro)).
pos(f(acbb,asoderberghsteven)).
pos(f(alucavitrano,adonatellafinocchiaro)).
pos(f(aauroraquattrocchi,acesareapolito)).
pos(f(aeddasabatini,bbba)).
pos(f(agutjahrrainer,athomasstielner)).
pos(f(amarkusbker,amarisaburger)).
pos(f(ajurneesmollett,anormanarmour)).
pos(f(aestefanacastro,avincentlecoeur)).
pos(f(acbc,apenlopecruz)).
pos(f(astevekuhn,cbbb)).
pos(f(akostatsonev,aemiliaradeva)).
pos(f(amiguelferrer,arobyndouglass)).
pos(f(asydneypollack,agretascacchi)).
pos(f(aarmelledeutsch,adidierdijoux)).
pos(f(acbb,atimothypaulperez)).
pos(f(adontiffany,cabc)).
pos(f(aauroraquattrocchi,adanielegalea)).
pos(f(asheilapaterson,agilbellows)).
pos(f(bcac,cbca)).
pos(f(aaltmanroberti,adeanstockwell)).
pos(f(asharonstone,amarccaleb)).
pos(f(astoychomazgalov,aangelinasarova)).
pos(f(astevekalfa,bbbc)).
pos(f(bacc,atimothypaulperez)).
pos(f(adannflorek,cbab)).
pos(f(afrankpatton,ascottcaan)).
pos(f(amarccaleb,acaitlinoheaney)).
pos(f(aleilanisarelle,amichaeldouglas)).
pos(f(aantoniettacarbonetti,afabiolobello)).
pos(f(abillyconnolly,cbab)).
pos(f(atonetticlaudio,astevekalfa)).
pos(f(ajuttawachowiak,avolkerranisch)).
pos(f(bccb,aclaudiamessner)).
pos(f(baaa,acba)).
pos(f(aellenthomas,cbbc)).
pos(f(aangelinasarova,akirilyanev)).
pos(f(aivantonev,abac)).
pos(f(aceceliaannbirt,ccca)).
pos(f(bbcc,apakulaalanj)).
pos(f(alloydalan,adebraengle)).
pos(f(amarcoleonardi,apaolaciampi)).
pos(f(akronthalerthomas,baac)).
pos(f(aarmelledeutsch,apierrearditi)).
pos(f(adeanstockwell,adinamerrill)).
pos(f(aludwigbriand,aarmelledeutsch)).
pos(f(aandygarcia,aannejacques)).
pos(f(alewissmith,cbbb)).
pos(f(asamshepard,cabb)).
pos(f(ajackmcgee,ajeannetripplehorn)).
pos(f(cbac,aemilmarkov)).
pos(f(amarksangster,ahughdancy)).
pos(f(acaseyaffleck,adinaconnolly)).
pos(f(achelcieross,awayneknight)).
pos(f(bcac,agrimaldiaurelioi)).
pos(f(aacb,aenzodimartino)).
pos(f(aklischstefan,aandreasschwaiger)).
pos(f(aandreasschwaiger,akonstanzebreitebner)).
pos(f(ccbc,aantoninobruschetta)).
pos(f(aangelinasarova,abcc)).
pos(f(atimberrington,aindiravarma)).
pos(f(bbba,apenlopecruz)).
pos(f(abrnicebejo,caba)).
pos(f(aleilanisarelle,adenisarndt)).
pos(f(aabc,avincentlecoeur)).
pos(f(akunkabaeva,astefanpejchev)).
pos(f(amillergeorgei,amiguelferrer)).
pos(f(acbc,araffaeladavi)).
pos(f(ccca,alorigalinski)).
pos(f(ascottcaan,acatherinezetajones)).
pos(f(acaseyaffleck,amarkgantt)).
pos(f(agesinecukrowski,ajrggudzuhn)).
pos(f(averhoevenpauli,abruceayoung)).
pos(f(akarinthaler,agerdlohmeyer)).
pos(f(apaullnolan,acaseyaffleck)).
pos(f(agiancarloscuderi,aacb)).
pos(f(bbca,anormanarmour)).
pos(f(babc,acba)).
pos(f(apetyasilyanova,akostatsonev)).
pos(f(aestefanacastro,caba)).
pos(f(aserenaautieri,abiagiobarone)).
pos(f(ccbb,aandreasschwaiger)).
pos(f(acca,abenjohnson)).
pos(f(cbac,akostatsonev)).
pos(f(amarkusbker,ccbb)).
pos(f(bbaa,aarmelledeutsch)).
pos(f(acab,astoychomazgalov)).
pos(f(avyarakovacheva,aganchoganchev)).
pos(f(asharonstone,aneilmaskell)).
pos(f(aileanarigano,accc)).
pos(f(aleahayres,apetergallagher)).
pos(f(adimitarhadzhiyanev,aemiliaradeva)).
pos(f(amarenschumacher,aandreasschwaiger)).
pos(f(arobyndouglass,ajustinmonjo)).
pos(f(acac,acarmelogalati)).
pos(f(cbba,ajeannetripplehorn)).
pos(f(amarksangster,aterenceharvey)).
pos(f(araffaeladavi,adanielegalea)).
pos(f(amillergeorgei,agusmercurio)).
pos(f(ccbb,ahubertmulzer)).
pos(f(caca,ascottcaan)).
pos(f(alloydalan,cbbb)).
pos(f(aluciasardo,avincenzocrivello)).
pos(f(astefanodionisi,aauroraquattrocchi)).
pos(f(aloccorbery,aabc)).
pos(f(bcab,asoderberghsteven)).
pos(f(abab,adanielegalea)).
pos(f(afrancomirabella,aenzodimartino)).
pos(f(bcac,apenlopecruz)).
pos(f(akrgnther,aandreasschwaiger)).
pos(f(acba,babc)).
pos(f(acaseyaffleck,atimothypaulperez)).
pos(f(acarmelogalati,aluciasardo)).
pos(f(bccb,atheresascholze)).
pos(f(cbca,adanielegalea)).
pos(f(caba,aabc)).
pos(f(adavidmorrissey,atimberrington)).
pos(f(aminianden,adavidsontag)).
pos(f(aaca,avincenzocrivello)).
pos(f(agabrieleferzetti,cccb)).
pos(f(aengelhardtwilhelm,aandreasschwaiger)).
pos(f(amarkgantt,acaseyaffleck)).
pos(f(ccbb,ahorstkummeth)).
pos(f(aianholm,bbca)).
pos(f(asharonstone,awayneknight)).
pos(f(azensmichael,aulrichmhe)).
pos(f(adavidsontag,aminianden)).
pos(f(astancollymore,amarksangster)).
pos(f(akarinthaler,amarkusbker)).
pos(f(amarcospicuglia,aluciasardo)).
pos(f(afrancishuster,astevekalfa)).
pos(f(afirminerichard,bcbc)).
pos(f(aleilanisarelle,abillcable)).
pos(f(bbab,apieradegliesposti)).
pos(f(bbaa,asamantharnier)).
pos(f(aacc,abac)).
pos(f(astefanodionisi,abbb)).
pos(f(cbac,bcbb)).
pos(f(adavidthewlis,afloramontgomery)).
pos(f(abba,agilbellows)).
pos(f(afloramontgomery,aneilmaskell)).
pos(f(cbac,astoychomazgalov)).
pos(f(aannejacques,acaseyaffleck)).
pos(f(amarinovichanton,anikoladadov)).
pos(f(avolkerranisch,akonstanzebreitebner)).
pos(f(asharonstone,aalancpeterson)).
pos(f(abradpitt,apaullnolan)).
pos(f(acharlotterampling,cbbc)).
pos(f(akirilyanev,ccaa)).
pos(f(amarkgantt,ageorgeclooney)).
pos(f(anevenakokanova,adimitarhadzhiyanev)).
pos(f(abac,atzvetolyubrakovski)).
pos(f(aivantonev,akunkabaeva)).
pos(f(aianholm,asheilapaterson)).
pos(f(amanliosgalambro,aannamariagherardi)).
pos(f(ageorgeclooney,acarolflorence)).
pos(f(acorradofortuna,aannamariagherardi)).
pos(f(akunkabaeva,aivantonev)).
pos(f(agusmercurio,cbbb)).
pos(f(astefandanailov,anevenakokanova)).
pos(f(ccac,adietermann)).
pos(f(atizianalodato,aantoninobruschetta)).
pos(f(ccca,asoderberghsteven)).
pos(f(astoychomazgalov,asonyadjulgerova)).
pos(f(aestefanacastro,aloccorbery)).
pos(f(aluciasardo,amarcocavicchioli)).
pos(f(ajurneesmollett,aianholm)).
pos(f(amarinovichanton,atzvetolyubrakovski)).
pos(f(aauroraquattrocchi,amarcoleonardi)).
pos(f(bcbc,ccab)).
pos(f(alylelovett,awhoopigoldberg)).
pos(f(atizianalodato,amanliosgalambro)).
pos(f(acbc,acba)).
pos(f(achelcieross,abillcable)).
pos(f(asharonstone,cbcc)).
pos(f(apatricejuiff,aabc)).
pos(f(abbb,astefanodionisi)).
pos(f(aantonradichev,cbac)).
pos(f(arenateschroeter,aulrichmhe)).
pos(f(bacb,acarmelogalati)).
pos(f(abca,asharonstone)).
pos(f(adorothymalone,ajackmcgee)).
pos(f(anevenakokanova,asotirmaynolovski)).
pos(f(acynthiastevenson,abrionjames)).
pos(f(amarksangster,adavidthewlis)).
pos(f(adinaconnolly,ajuliaroberts)).
pos(f(ajrggudzuhn,akonstanzebreitebner)).
pos(f(astefanodionisi,acba)).
pos(f(cbab,agilbellows)).
pos(f(abcc,aangelinasarova)).
pos(f(agrimaldiaurelioi,bcca)).
pos(f(caac,apieradegliesposti)).
pos(f(aivangrigorov,asonyadjulgerova)).
pos(f(asoderberghsteven,aedkross)).
pos(f(ametcalfestephen,aalancpeterson)).
pos(f(aulrichmhe,ajuttawachowiak)).
pos(f(cbba,asharonstone)).
pos(f(agrimaldiaurelioi,avincenzocrivello)).
pos(f(aauroraquattrocchi,acbc)).
pos(f(aantoniettacarbonetti,bcca)).
pos(f(amarenschumacher,atommikulla)).
pos(f(aarmelledeutsch,apatricejuiff)).
pos(f(bcaa,ajustinmonjo)).
pos(f(astancollymore,afloramontgomery)).
pos(f(bbab,afrancomirabella)).
pos(f(aklischstefan,agerdlohmeyer)).
pos(f(astanleyanderson,cabb)).
pos(f(aaaa,aangelahall)).
pos(f(avincentlecoeur,aalexandrawinisky)).
pos(f(avincentlecoeur,abrnicebejo)).
pos(f(abab,astefanodionisi)).
pos(f(abradpitt,ajorgerhernandez)).
pos(f(agretascacchi,asydneypollack)).
pos(f(bcab,aeddiejemison)).
pos(f(abbc,aaca)).
pos(f(aalexandrawinisky,apatricejuiff)).
pos(f(acarmelogalati,aluciacammalleri)).
pos(f(aluciasardo,caac)).
pos(f(aestefanacastro,bbaa)).
pos(f(cbca,bbba)).
pos(f(akunkabaeva,astefanpetrov)).
pos(f(araffaeladavi,bcac)).
pos(f(afloramontgomery,adavidthewlis)).
pos(f(asharonstone,adenisarndt)).
pos(f(bcaa,astevekuhn)).
pos(f(adontiffany,aannejacques)).
pos(f(amikhailmikhajlov,acab)).
pos(f(apakulaalanj,ajamessikking)).
pos(f(afrankpatton,ageorgeclooney)).
pos(f(avincentlecoeur,ajuliedray)).
pos(f(abba,afrankcturner)).
pos(f(ajanchappell,aindiravarma)).
pos(f(ccbb,atommikulla)).
pos(f(atraykovatanas,apetardespotov)).
pos(f(aginachiarelli,adillonmoen)).
pos(f(accc,abarbaratabita)).
pos(f(ccba,aestefanacastro)).
pos(f(asurchadzhievstefani,ahristodinev)).
pos(f(ajackmcgee,asharonstone)).
pos(f(apakulaalanj,accb)).
pos(f(alucavitrano,anicolegrimaudo)).
pos(f(cccc,aabb)).
pos(f(adillonmoen,asharonstone)).
pos(f(ccbc,acorradofortuna)).
pos(f(aradarassimov,cccb)).
pos(f(amarcocavicchioli,apieradegliesposti)).
pos(f(asamantharnier,avincentlecoeur)).
pos(f(ccaa,amikhailmikhajlov)).
pos(f(atheresascholze,ajrggudzuhn)).
pos(f(aelliottgould,abaa)).
pos(f(agabriellelazure,bcbc)).
pos(f(alarrysontag,aminianden)).
pos(f(adillonmoen,bbca)).
pos(f(bbab,aaca)).
pos(f(astefanpejchev,amariashopova)).
pos(f(aguillaumeromain,abrigittefossey)).
pos(f(ascottcaan,aceceliaannbirt)).
pos(f(avolkerranisch,arenateschroeter)).
pos(f(aianholm,abba)).
pos(f(aconsuelolupo,abarbaratabita)).
pos(f(asharonstone,ahughkeaysbyrne)).
pos(f(ccaa,ahristodinev)).
pos(f(aantoniettacarbonetti,amaurizionicolosi)).
pos(f(cccb,aradarassimov)).
pos(f(caca,ageorgeclooney)).
pos(f(apierrearditi,aestefanacastro)).
pos(f(abcb,aapprederisfranck)).
pos(f(aginachiarelli,cbcc)).
pos(f(aabc,aloccorbery)).
pos(f(agutjahrrainer,amaxmller)).
pos(f(acynthiastevenson,arichardegrant)).
pos(f(astevekuhn,arobyndouglass)).
pos(f(asalvatorelazzaro,aaca)).
pos(f(atizianalodato,cccb)).
pos(f(apakulaalanj,arobertculp)).
pos(f(alaurabetti,adanielegalea)).
pos(f(aapprederisfranck,aguillaumeromain)).
pos(f(abcc,asurchadzhievstefani)).
pos(f(afloramontgomery,babb)).
pos(f(adanielegalea,aauroraquattrocchi)).
pos(f(bcab,aberniemac)).
pos(f(aromeclaudemichel,bcbc)).
pos(f(cbaa,atommikulla)).
pos(f(avolkerranisch,atheresascholze)).
pos(f(aannejacques,ageorgeclooney)).
pos(f(aeddasabatini,astefanodionisi)).
pos(f(abradpitt,aannejacques)).
pos(f(agutjahrrainer,baac)).
pos(f(apieradegliesposti,aenzodimartino)).
pos(f(bacc,aberniemac)).
pos(f(amarinovichanton,bbcb)).
pos(f(anormanarmour,aginachiarelli)).
pos(f(aaac,aminianden)).
pos(f(ajanchappell,babb)).
pos(f(akrgnther,atommikulla)).
pos(f(abraunbettinai,agerdlohmeyer)).
pos(f(amanliosgalambro,aluciasardo)).
pos(f(abiagiobarone,abarbaratabita)).
pos(f(alewissmith,bcaa)).
pos(f(bbbb,awhoopigoldberg)).
pos(f(baac,abraunbettinai)).
pos(f(asoderberghsteven,bcab)).
pos(f(ahughkeaysbyrne,acaitlinoheaney)).
pos(f(amarccaleb,asharonstone)).
pos(f(acaitlinoheaney,amarccaleb)).
pos(f(adeanstockwell,agretascacchi)).
pos(f(azensmichael,bccb)).
pos(f(adillonmoen,aginachiarelli)).
pos(f(aceceliaannbirt,abaa)).
pos(f(astefanpejchev,avyarakovacheva)).
pos(f(aellenthomas,babb)).
pos(f(aleahayres,afredward)).
pos(f(acharlotterampling,ahughdancy)).
pos(f(apunchevborislav,bcbb)).
pos(f(ajrggudzuhn,agesinecukrowski)).
pos(f(apunchevborislav,bbac)).
pos(f(babc,araffaeladavi)).
pos(f(asharonstone,agusmercurio)).
pos(f(aladogedominique,bcbc)).
pos(f(alloydalan,acaitlinoheaney)).
pos(f(arobyndouglass,alewissmith)).
pos(f(aaba,acharlotterampling)).
pos(f(aminianden,cacb)).
pos(f(accc,aileanarigano)).
pos(f(acatonjonesmichael,aterenceharvey)).
pos(f(asharonstone,anormanarmour)).
pos(f(ajannowicki,cbac)).
pos(f(astephanbernhard,adietermann)).
pos(f(ascottcaan,aberniemac)).
pos(f(cbbb,amarccaleb)).
pos(f(anikoladadov,avyarakovacheva)).
pos(f(aengelhardtwilhelm,athomasstielner)).
pos(f(ajurneesmollett,ajaimzwoolvett)).
pos(f(caaa,agusmercurio)).
pos(f(aklischstefan,amarkusbker)).
pos(f(adorothymalone,cbba)).
pos(f(ccaa,alyubomirbobchevski)).
pos(f(aelliottgould,bcab)).
pos(f(aantoninobruschetta,anicolegrimaudo)).
pos(f(aacc,amarinovichanton)).
pos(f(adinaconnolly,adavidsontag)).
pos(f(baaa,abbb)).
pos(f(agretascacchi,apetergallagher)).
pos(f(aheathcotewilliams,afloramontgomery)).
pos(f(alloydalan,asharonstone)).
pos(f(ajackmcgee,adorothymalone)).
pos(f(aabb,acca)).
pos(f(agesinecukrowski,avolkerranisch)).
pos(f(ajeannetripplehorn,astephentobolowsky)).
pos(f(asoderberghsteven,bacc)).
pos(f(atimberrington,cbbc)).
pos(f(adenisarndt,aleilanisarelle)).
pos(f(acbb,acarolflorence)).
pos(f(astoychomazgalov,aemiliaradeva)).
pos(f(ageorgeclooney,aberniemac)).
pos(f(acba,acbc)).
pos(f(aginachiarelli,adannflorek)).
pos(f(awhoopigoldberg,caab)).
pos(f(aabc,apatricejuiff)).
pos(f(acaseyaffleck,aelliottgould)).
pos(f(amaurizionicolosi,aacb)).
pos(f(aluciasardo,alucavitrano)).
pos(f(asharonstone,aianholm)).
pos(f(ahughkeaysbyrne,arobyndouglass)).
pos(f(aginachiarelli,anormanarmour)).
pos(f(acharlotterampling,adavidmorrissey)).
pos(f(ajurneesmollett,abenjohnson)).
pos(f(aabb,ametcalfestephen)).
pos(f(cabb,aanthonyheald)).
pos(f(cbac,ajannowicki)).
pos(f(adavidarnett,caaa)).
pos(f(aannejacques,aandygarcia)).
pos(f(acesareapolito,aauroraquattrocchi)).
pos(f(cbbb,alloydalan)).
pos(f(caaa,amarccaleb)).
pos(f(acab,cbcb)).
pos(f(aanthonyheald,cabb)).
pos(f(adidierdijoux,ajuliedray)).
pos(f(adanielegalea,acba)).
pos(f(cbcc,ajurneesmollett)).
pos(f(aantonradichev,aalicjajachiewicz)).
pos(f(apenlopecruz,babc)).
pos(f(aacc,akunkabaeva)).
pos(f(agretascacchi,adeanstockwell)).
pos(f(avincentlecoeur,asamantharnier)).
pos(f(acaseyaffleck,afrankpatton)).
pos(f(apakulaalanj,asamshepard)).
pos(f(atimothypaulperez,abaa)).
pos(f(aluciasardo,bbab)).
pos(f(agretascacchi,bbbb)).
pos(f(cbab,aabb)).
pos(f(aalicjajachiewicz,amichalbajor)).
pos(f(averhoevenpauli,bcba)).
pos(f(atimothypaulperez,abradpitt)).
pos(f(apakulaalanj,astanleyanderson)).
pos(f(afloramontgomery,aaba)).
pos(f(asydneypollack,aangelahall)).
pos(f(azensmichael,aleonardlansink)).
pos(f(accc,aluciacammalleri)).
pos(f(aberniemac,ccca)).
pos(f(bccb,akonstanzebreitebner)).
pos(f(bcbb,anevenakokanova)).
pos(f(aminianden,acaseyaffleck)).
pos(f(baaa,apaolaciampi)).
pos(f(cccb,atizianalodato)).
pos(f(abarbaratabita,accc)).
pos(f(anormanarmour,cccc)).
pos(f(ajeannetripplehorn,ageorgedzundza)).
pos(f(avannifois,aluciasardo)).
pos(f(bbbb,aleahayres)).
pos(f(avergnejeanpierre,aludwigbriand)).
pos(f(asotirmaynolovski,aalicjajachiewicz)).
pos(f(apierrearditi,aarmelledeutsch)).
pos(f(aacb,afabiolobello)).
pos(f(afrancomirabella,afabiolobello)).
pos(f(amarcoleonardi,abab)).
pos(f(cbbb,alewissmith)).
pos(f(atheresascholze,adietermann)).
pos(f(aluciasardo,asaromiano)).
pos(f(ccbc,amanliosgalambro)).
pos(f(aloccorbery,aarmelledeutsch)).
pos(f(afrancomirabella,amarcocavicchioli)).
pos(f(asurchadzhievstefani,cbcb)).
pos(f(asavahashamov,aangelinasarova)).
pos(f(caaa,amiguelferrer)).
pos(f(apakulaalanj,ahumecronyn)).
pos(f(cbbb,amiguelferrer)).
pos(f(abenjohnson,cccc)).
pos(f(akostatsonev,apetyasilyanova)).
pos(f(aheathcotewilliams,atimberrington)).
pos(f(afrankcturner,asharonstone)).
pos(f(apetergallagher,aleahayres)).
pos(f(adavidthewlis,ajanchappell)).
pos(f(aalexandrawinisky,ccba)).
pos(f(aleahayres,caab)).
pos(f(aannamariagherardi,cccb)).
pos(f(ajohnheard,cabb)).
pos(f(afrancomirabella,amaurizionicolosi)).
pos(f(caca,acbb)).
pos(f(ageorgeclooney,acatherinezetajones)).
pos(f(asaromiano,afrancomirabella)).
pos(f(abac,bbcb)).
pos(f(akronthalerthomas,atommikulla)).
pos(f(aleonardlansink,atheresascholze)).
pos(f(bcaa,alewissmith)).
pos(f(agrimaldiaurelioi,asalvatorelazzaro)).
pos(f(aleonardlansink,agesinecukrowski)).
pos(f(aeddasabatini,amarcoleonardi)).
pos(f(baac,akinkelmartin)).
pos(f(adanielvonbargen,asharonstone)).
pos(f(agusmercurio,asharonstone)).
pos(f(aacb,amarcospicuglia)).
pos(f(akarinthaler,aandreasschwaiger)).
pos(f(apierrearditi,abrnicebejo)).
pos(f(ccba,baca)).
pos(f(avincentdonofrio,awhoopigoldberg)).
pos(f(abonnetchristiani,bcbc)).
pos(f(amarisaburger,amarkusbker)).
pos(f(acaitlinoheaney,alloydalan)).
pos(f(awhoopigoldberg,alylelovett)).
pos(f(apunchevborislav,acaa)).
pos(f(acba,bbba)).
pos(f(ageorgedzundza,ajeannetripplehorn)).
pos(f(afrancomirabella,avincenzocrivello)).
pos(f(akarinthaler,ahubertmulzer)).
pos(f(abab,amarcoleonardi)).
pos(f(adenisarndt,adorothymalone)).
pos(f(abillyconnolly,ajurneesmollett)).
pos(f(aellenthomas,aterenceharvey)).
pos(f(anormanarmour,abba)).
pos(f(apieradegliesposti,amaurizionicolosi)).
pos(f(apetyasilyanova,aivangrigorov)).
pos(f(asoderberghsteven,cacb)).
pos(f(bacb,aconsuelolupo)).
pos(f(apieradegliesposti,caac)).
pos(f(aganchoganchev,abac)).
pos(f(aheathcotewilliams,amarksangster)).
pos(f(astefanpetrov,akunkabaeva)).
pos(f(atraykovatanas,adimitarhadzhiyanev)).
pos(f(aulrichmhe,atheresascholze)).
pos(f(bcba,achelcieross)).
pos(f(acharlotterampling,aterenceharvey)).
pos(f(abac,astefanpejchev)).
pos(f(agerdlohmeyer,amarisaburger)).
pos(f(cbcc,acca)).
pos(f(apetergallagher,awhoopigoldberg)).
pos(f(acarmelogalati,baab)).
pos(f(ccba,aarmelledeutsch)).
pos(f(atimothypaulperez,ccca)).
pos(f(ahughkeaysbyrne,adebraengle)).
pos(f(aelliottgould,ageorgeclooney)).
pos(f(abenjohnson,acca)).
pos(f(cbca,babc)).
pos(f(akinkelmartin,amaxmller)).
pos(f(adorothymalone,abenjaminmouton)).
pos(f(acaseyaffleck,apaullnolan)).
pos(f(bcab,acarolflorence)).
pos(f(ccac,aulrichmhe)).
pos(f(aivanbratanov,aangelinasarova)).
pos(f(ccba,avergnejeanpierre)).
pos(f(abradpitt,adinaconnolly)).
pos(f(abba,aabb)).
pos(f(ccac,ajrggudzuhn)).
pos(f(abrnicebejo,ccba)).
pos(f(atommikulla,ccbb)).
pos(f(abcb,abrnicebejo)).
pos(f(babc,apaolaciampi)).
pos(f(aklischstefan,amaxmller)).
pos(f(alorigalinski,ascottcaan)).
pos(f(acba,astefanodionisi)).
pos(f(bcba,averhoevenpauli)).
pos(f(akronthalerthomas,athomasstielner)).
pos(f(aaab,aradarassimov)).
pos(f(anelsonpeltz,aannejacques)).
pos(f(aantoniettacarbonetti,asaromiano)).
pos(f(anevenakokanova,acaa)).
pos(f(bbbb,aaltmanroberti)).
pos(f(aantoniettacarbonetti,aenzodimartino)).
pos(f(aestefanacastro,bccc)).
pos(f(adannflorek,acca)).
pos(f(bccc,aestefanacastro)).
pos(f(atimrobbins,awhoopigoldberg)).
pos(f(apunchevborislav,akostatsonev)).
pos(f(aneilmaskell,aellenthomas)).
pos(f(acorradofortuna,adonatellafinocchiaro)).
pos(f(amarcospicuglia,aantoniettacarbonetti)).
pos(f(amillergeorgei,alewissmith)).
pos(f(abbb,adanielegalea)).
pos(f(cbab,adillonmoen)).
pos(f(aacb,amarcocavicchioli)).
pos(f(atimothypaulperez,acbb)).
pos(f(cabb,asamshepard)).
pos(f(awhoopigoldberg,adeanstockwell)).
pos(f(aenzodimartino,afrancomirabella)).
pos(f(awayneknight,ajeannetripplehorn)).
pos(f(abenjohnson,ajurneesmollett)).
pos(f(aaab,adonatellafinocchiaro)).
pos(f(amarisaburger,ahorstkummeth)).
pos(f(bcbc,afrancishuster)).
pos(f(aeddasabatini,babc)).
pos(f(ccba,abrnicebejo)).
pos(f(asamantharnier,ccba)).
pos(f(apaolaciampi,acesareapolito)).
pos(f(aguillaumeromain,aarmelledeutsch)).
pos(f(asharonstone,aterenceharvey)).
pos(f(alewissmith,arobyndouglass)).
pos(f(adebraengle,alloydalan)).
pos(f(aindiravarma,atimberrington)).
pos(f(abarbaratabita,aconsuelolupo)).
pos(f(avincentdonofrio,aleahayres)).
pos(f(amaurizionicolosi,afrancomirabella)).
pos(f(aluciacammalleri,acarmelogalati)).
pos(f(agesinecukrowski,aleonardlansink)).
pos(f(aannejacques,adontiffany)).
pos(f(adebraengle,amiguelferrer)).
pos(f(cbcb,acab)).
pos(f(ajaimzwoolvett,abba)).
pos(f(amarenschumacher,ahorstkummeth)).
pos(f(adietermann,aclaudiamessner)).
pos(f(acharlotterampling,adavidthewlis)).
pos(f(agrimaldiaurelioi,bbab)).
pos(f(aemilmarkov,anevenakokanova)).
pos(f(aaltmanroberti,caab)).
pos(f(caba,avergnejeanpierre)).
pos(f(aleonardlansink,akonstanzebreitebner)).
pos(f(caca,ccca)).
pos(f(bbca,aconnorwiddows)).
pos(f(ccac,bccb)).
pos(f(adonatellafinocchiaro,acorradofortuna)).
pos(f(atraykovatanas,akostatsonev)).
pos(f(bbba,alaurabetti)).
pos(f(aluciasardo,avannifois)).
pos(f(aapprederisfranck,abcb)).
pos(f(adonatellafinocchiaro,alucavitrano)).
pos(f(accc,amanueladolcemascolo)).
pos(f(bccb,ajuttawachowiak)).
pos(f(aindiravarma,aellenthomas)).
pos(f(ccaa,aviktordanchenko)).
pos(f(amanliosgalambro,ccbc)).
pos(f(aenzodimartino,aluciasardo)).
pos(f(asheilapaterson,afrankcturner)).
pos(f(aianholm,ajurneesmollett)).
pos(f(adannflorek,asharonstone)).
pos(f(aauroraquattrocchi,baaa)).
pos(f(acatherinezetajones,aaac)).
pos(f(apierrearditi,ajuliedray)).
pos(f(arichardegrant,adinamerrill)).
pos(f(adorothymalone,adenisarndt)).
pos(f(aapprederisfranck,apierrearditi)).
pos(f(agusmercurio,arobyndouglass)).
pos(f(aenzodimartino,aantoniettacarbonetti)).
pos(f(baca,aloccorbery)).
pos(f(abab,acbc)).
pos(f(acatonjonesmichael,adavidthewlis)).
pos(f(babb,acharlotterampling)).
pos(f(atizianalodato,acorradofortuna)).
pos(f(cbbb,ahughkeaysbyrne)).
pos(f(anevenakokanova,astefandanailov)).
pos(f(asharonstone,astephentobolowsky)).
pos(f(acynthiastevenson,caab)).
pos(f(adebraengle,adavidarnett)).
pos(f(aalicjajachiewicz,bcbb)).
pos(f(aaab,agabrieleferzetti)).
pos(f(acbc,aeddasabatini)).
pos(f(avincentlecoeur,aestefanacastro)).
pos(f(adavidmorrissey,aellenthomas)).
pos(f(apenlopecruz,acbc)).
pos(f(ascottcaan,atimothypaulperez)).
pos(f(cbbc,aellenthomas)).
pos(f(achelcieross,ageorgedzundza)).
pos(f(amarinovichanton,aivantonev)).
pos(f(cacb,asoderberghsteven)).
pos(f(aemiliaradeva,astefandanailov)).
pos(f(bcbc,afirminerichard)).
pos(f(cabc,cacb)).
pos(f(acaseyaffleck,aceceliaannbirt)).
pos(f(bacc,caca)).
pos(f(bcca,agrimaldiaurelioi)).
pos(f(agutjahrrainer,aandreasschwaiger)).
pos(f(atimberrington,aaba)).
pos(f(atommikulla,amarisaburger)).
pos(f(aalancpeterson,ajurneesmollett)).
pos(f(anormanarmour,cbab)).
pos(f(amarcospicuglia,aacb)).
pos(f(ccac,avolkerranisch)).
pos(f(aguillaumeromain,aestefanacastro)).
pos(f(aapprederisfranck,apatricejuiff)).
pos(f(bacc,amarkgantt)).
pos(f(bcac,abab)).
pos(f(caac,afrancomirabella)).
pos(f(bcbc,aromeclaudemichel)).
pos(f(abba,aianholm)).
pos(f(aguillaumeromain,baca)).
pos(f(aclaudiamessner,bccb)).
pos(f(acac,avannifois)).
pos(f(afredward,aangelahall)).
pos(f(cccc,adillonmoen)).
pos(f(babc,aauroraquattrocchi)).
pos(f(ajustinmonjo,adebraengle)).
pos(f(ajuliedray,aludwigbriand)).
pos(f(apaolaciampi,bcac)).
pos(f(abbb,bbba)).
pos(f(asavahashamov,ccaa)).
pos(f(amanliosgalambro,anicolegrimaudo)).
pos(f(afrankcturner,abba)).
pos(f(aleilanisarelle,astephentobolowsky)).
pos(f(amanliosgalambro,adonatellafinocchiaro)).
pos(f(bbaa,aalexandrawinisky)).
pos(f(alaurabetti,baaa)).
pos(f(aaba,asharonstone)).
pos(f(abbb,bcac)).
pos(f(atimberrington,aheathcotewilliams)).
pos(f(adebraengle,alewissmith)).
pos(f(aangelahall,caab)).
pos(f(abrigittefossey,avincentlecoeur)).
pos(f(adavidthewlis,amarksangster)).
pos(f(aguillaumeromain,asamantharnier)).
pos(f(acaseyaffleck,aberniemac)).
pos(f(akonstanzebreitebner,aleonardlansink)).
pos(f(avolkerranisch,agesinecukrowski)).
pos(f(bcbb,aalicjajachiewicz)).
pos(f(avergnejeanpierre,aguillaumeromain)).
pos(f(aterenceharvey,atimberrington)).
pos(f(aellenthomas,aindiravarma)).
pos(f(amarinovichanton,ageorgistamatov)).
pos(f(asoderberghsteven,alarrysontag)).
pos(f(ccba,asamantharnier)).
pos(f(aconsuelolupo,aluciacammalleri)).
pos(f(aterenceharvey,acharlotterampling)).
pos(f(akarinthaler,athomasstielner)).
pos(f(bcbc,cacc)).
pos(f(alylelovett,aleahayres)).
pos(f(astephentobolowsky,asharonstone)).
pos(f(alewissmith,asharonstone)).
pos(f(apetardespotov,asonyadjulgerova)).
pos(f(aludwigbriand,ajuliedray)).
pos(f(aklischstefan,ahubertmulzer)).
pos(f(ascottcaan,acarolflorence)).
pos(f(aivangrigorov,aemiliaradeva)).
pos(f(aarmelledeutsch,bbaa)).
pos(f(alloydalan,caaa)).
pos(f(aivanbratanov,abac)).
pos(f(abbc,aluciasardo)).
pos(f(ajurneesmollett,adannflorek)).
pos(f(ajaimzwoolvett,asheilapaterson)).
pos(f(atzenokandov,ccaa)).
pos(f(bbca,agilbellows)).
pos(f(apieradegliesposti,asalvatorelazzaro)).
pos(f(bbba,araffaeladavi)).
pos(f(abiagiobarone,bacb)).
pos(f(abillcable,ajeannetripplehorn)).
pos(f(amarccaleb,adebraengle)).
pos(f(cabb,ahumecronyn)).
pos(f(aheathcotewilliams,acharlotterampling)).
pos(f(acaitlinoheaney,ahughkeaysbyrne)).
pos(f(ajuliedray,apierrearditi)).
pos(f(bbbb,adinamerrill)).
pos(f(cbaa,ahorstkummeth)).
pos(f(adanielegalea,aeddasabatini)).
pos(f(aangelinasarova,cbcb)).
pos(f(aangelahall,atimrobbins)).
pos(f(averhoevenpauli,ageorgedzundza)).
pos(f(atommikulla,amarenschumacher)).
pos(f(bbca,ajaimzwoolvett)).
pos(f(aalicjajachiewicz,abogomilsimeonov)).
pos(f(anevenakokanova,aemilmarkov)).
pos(f(baaa,araffaeladavi)).
pos(f(aaab,aluciasardo)).
pos(f(aulrichmhe,aclaudiamessner)).
pos(f(adinamerrill,afredward)).
pos(f(arenateschroeter,avolkerranisch)).
pos(f(apakulaalanj,ajohnfinn)).
pos(f(baac,cbaa)).
pos(f(acarmelogalati,aserenaautieri)).
pos(f(apunchevborislav,amichalbajor)).
pos(f(bcac,acba)).
pos(f(aantoniettacarbonetti,caac)).
pos(f(aantoninobruschetta,aradarassimov)).
pos(f(aemilmarkov,aalicjajachiewicz)).
pos(f(ascottcaan,adinaconnolly)).
pos(f(akostatsonev,asonyadjulgerova)).
pos(f(asharonstone,cbbc)).
pos(f(athomasstielner,cbaa)).
pos(f(ahubertmulzer,amarisaburger)).
pos(f(adinamerrill,apetergallagher)).
pos(f(ametcalfestephen,aabb)).
pos(f(amaurolenares,aantoniettacarbonetti)).
pos(f(awhoopigoldberg,afredward)).
pos(f(aeddiejemison,abradpitt)).
pos(f(abrnicebejo,avincentlecoeur)).
pos(f(achelcieross,astephentobolowsky)).
pos(f(aleahayres,bbbb)).
pos(f(adorothymalone,amichaeldouglas)).
pos(f(aacb,amaurolenares)).
pos(f(bbac,cbac)).
pos(f(abillyconnolly,asharonstone)).
pos(f(adietermann,atheresascholze)).
pos(f(astoychomazgalov,cbac)).
pos(f(abenjohnson,aginachiarelli)).
pos(f(adavidthewlis,atimberrington)).
pos(f(acarolflorence,acaseyaffleck)).
pos(f(asharonstone,aaba)).
pos(f(aserenaautieri,avannifois)).
pos(f(abattiatofranco,alucavitrano)).
pos(f(abcb,aabc)).
pos(f(bcab,aelliottgould)).
pos(f(amichaeldouglas,aleilanisarelle)).
pos(f(apunchevborislav,aantonradichev)).
pos(f(acaa,aalicjajachiewicz)).
pos(f(acba,adanielegalea)).
pos(f(accb,apakulaalanj)).
pos(f(aeddasabatini,acesareapolito)).
pos(f(aestefanacastro,abcb)).
pos(f(apatricejuiff,aarmelledeutsch)).
pos(f(asheilapaterson,adillonmoen)).
pos(f(aandreasschwaiger,ajuttawachowiak)).
pos(f(apaolaciampi,baaa)).
pos(f(abrigittefossey,ccba)).
pos(f(abcb,abrigittefossey)).
pos(f(acbc,agrimaldiaurelioi)).
pos(f(aconnorwiddows,acca)).
pos(f(ajustinmonjo,bcaa)).
pos(f(aedkross,cabc)).
pos(f(apetardespotov,aemiliaradeva)).
pos(f(baaa,apenlopecruz)).
pos(f(aelliottgould,abradpitt)).
pos(f(acorradofortuna,anicolegrimaudo)).
pos(f(aceceliaannbirt,acaseyaffleck)).
pos(f(aabc,ccba)).
pos(f(aarmelledeutsch,aludwigbriand)).
pos(f(agusmercurio,bcaa)).
pos(f(aalexandrawinisky,aguillaumeromain)).
pos(f(accc,acac)).
pos(f(aandreasschwaiger,atheresascholze)).
pos(f(aaca,amarcocavicchioli)).
pos(f(aangelinasarova,atzenokandov)).
pos(f(alorigalinski,bcab)).
pos(f(avergnejeanpierre,ccba)).
pos(f(amarinovichanton,aacc)).
pos(f(adanielegalea,araffaeladavi)).
pos(f(awayneknight,achelcieross)).
pos(f(cbbc,asharonstone)).
pos(f(agabriellelazure,astevekalfa)).
pos(f(aalicjajachiewicz,akostatsonev)).
pos(f(agrimaldiaurelioi,acbc)).
pos(f(cbab,adannflorek)).
pos(f(atimberrington,ahughdancy)).
pos(f(amaurolenares,afrancomirabella)).
pos(f(aleilanisarelle,abruceayoung)).
pos(f(bcaa,amiguelferrer)).
pos(f(adannflorek,cccc)).
pos(f(ccca,aceceliaannbirt)).
pos(f(aaaa,adinamerrill)).
pos(f(acatonjonesmichael,cbbc)).
pos(f(acca,aalancpeterson)).
pos(f(acbb,ajorgerhernandez)).
pos(f(amarisaburger,aandreasschwaiger)).
pos(f(anevenakokanova,aantonradichev)).
pos(f(asonyadjulgerova,astoychomazgalov)).
pos(f(astevekalfa,agabriellelazure)).
pos(f(apieradegliesposti,amarcocavicchioli)).
pos(f(akinkelmartin,atommikulla)).
pos(f(asharonstone,abenjohnson)).
pos(f(aabc,bccc)).
pos(f(cbbc,atimberrington)).
pos(f(caba,aalexandrawinisky)).
pos(f(aluciasardo,cccb)).
pos(f(abaa,aeddiejemison)).
pos(f(acynthiastevenson,avincentdonofrio)).
pos(f(aapprederisfranck,aludwigbriand)).
pos(f(aaaa,aaltmanroberti)).
pos(f(baca,caba)).
pos(f(asharonstone,amiguelferrer)).
pos(f(agiancarloscuderi,aluciasardo)).
pos(f(asydneypollack,acynthiastevenson)).
pos(f(cbcc,aginachiarelli)).
pos(f(acab,alyubomirbobchevski)).
pos(f(akonstanzebreitebner,adietermann)).
pos(f(aalicjajachiewicz,aantonradichev)).
pos(f(apakulaalanj,ajohnheard)).
pos(f(ametcalfestephen,abca)).
pos(f(asharonstone,adavidthewlis)).
pos(f(acharlotterampling,astancollymore)).
pos(f(aengelhardtwilhelm,amaxmller)).
pos(f(abbb,babc)).
pos(f(abiagiobarone,baab)).
pos(f(ajeannetripplehorn,bcba)).
pos(f(adidierdijoux,aabc)).
pos(f(acharlotterampling,aindiravarma)).
pos(f(afredward,adinamerrill)).
pos(f(aclaudiamessner,adietermann)).
pos(f(aangelinasarova,aivantonev)).
pos(f(agilbellows,acca)).
pos(f(baca,bbaa)).
pos(f(arobyndouglass,ahughkeaysbyrne)).
pos(f(abrigittefossey,caba)).
pos(f(acca,abillyconnolly)).
pos(f(anicolegrimaudo,aantoninobruschetta)).
pos(f(ametcalfestephen,afrankcturner)).
pos(f(apenlopecruz,bcac)).
pos(f(asonyadjulgerova,akostatsonev)).
pos(f(amarcospicuglia,aaca)).
pos(f(astefanodionisi,araffaeladavi)).
pos(f(amarcospicuglia,apieradegliesposti)).
pos(f(achelcieross,cbba)).
pos(f(aaltmanroberti,aaaa)).
pos(f(abiagiobarone,acac)).
pos(f(ajorgerhernandez,ascottcaan)).
pos(f(anikoladadov,aangelinasarova)).
pos(f(aluciacammalleri,aconsuelolupo)).
pos(f(aestefanacastro,apierrearditi)).
pos(f(cbab,aalancpeterson)).
pos(f(ajorgerhernandez,abradpitt)).
pos(f(ajorgerhernandez,ccca)).
pos(f(apunchevborislav,abogomilsimeonov)).
pos(f(ahristodinev,acab)).
pos(f(ahubertmulzer,amarenschumacher)).
pos(f(aneilmaskell,afloramontgomery)).
pos(f(bccc,aalexandrawinisky)).
pos(f(asurchadzhievstefani,abcc)).
pos(f(ajuliaroberts,aminianden)).
pos(f(adanielegalea,abbb)).
pos(f(abac,aivandimov)).
pos(f(caac,aantoniettacarbonetti)).
pos(f(agretascacchi,abrionjames)).
pos(f(aleahayres,asydneypollack)).
pos(f(ahughkeaysbyrne,caaa)).
pos(f(acesareapolito,alaurabetti)).
pos(f(apetergallagher,adinamerrill)).
pos(f(adonatellafinocchiaro,aaab)).
pos(f(cccc,afrankcturner)).
pos(f(ametcalfestephen,adillonmoen)).
pos(f(abab,bcac)).
pos(f(awhoopigoldberg,atimrobbins)).
pos(f(abradpitt,atimothypaulperez)).
pos(f(akronthalerthomas,amarkusbker)).
pos(f(apenlopecruz,acesareapolito)).
pos(f(aalexandrawinisky,adidierdijoux)).
pos(f(bcbc,baba)).
pos(f(aleonardlansink,ccac)).
pos(f(arichardegrant,aangelahall)).
pos(f(aangelinasarova,aacc)).
pos(f(caca,acaseyaffleck)).
pos(f(acynthiastevenson,afredward)).
pos(f(ajaimzwoolvett,aginachiarelli)).
pos(f(alaurabetti,acbc)).
pos(f(babc,apenlopecruz)).
pos(f(apenlopecruz,bbba)).
pos(f(apunchevborislav,asotirmaynolovski)).
pos(f(caac,aaca)).
pos(f(bbac,apunchevborislav)).
pos(f(aapprederisfranck,bccc)).
pos(f(acharlotterampling,aneilmaskell)).
pos(f(avyarakovacheva,aivanbratanov)).
pos(f(aalancpeterson,aginachiarelli)).
pos(f(arichardegrant,awhoopigoldberg)).
pos(f(bbaa,avergnejeanpierre)).
pos(f(aestefanacastro,ccba)).
pos(f(afloramontgomery,ahughdancy)).
pos(f(caba,aapprederisfranck)).
pos(f(aivantonev,amariashopova)).
pos(f(akonstanzebreitebner,aandreasschwaiger)).
pos(f(aulrichmhe,arenateschroeter)).
pos(f(aalancpeterson,cbab)).
pos(f(afloramontgomery,aindiravarma)).
pos(f(alyubomirbachvarov,aalicjajachiewicz)).
pos(f(aabc,caba)).
pos(f(aangelinasarova,atzvetolyubrakovski)).
pos(f(aannejacques,cacb)).
pos(f(abab,acesareapolito)).
pos(f(aneilmaskell,acharlotterampling)).
pos(f(apakulaalanj,bbcc)).
pos(f(athomasstielner,amarenschumacher)).
pos(f(cccb,agabrieleferzetti)).
pos(f(aganchoganchev,aangelinasarova)).
pos(f(agretascacchi,arichardegrant)).
pos(f(aarmelledeutsch,abcb)).
pos(f(baca,abcb)).
pos(f(atimberrington,babb)).
pos(f(aaca,aenzodimartino)).
pos(f(cbab,ajaimzwoolvett)).
pos(f(aconsuelolupo,baab)).
pos(f(aantoninobruschetta,aannamariagherardi)).
pos(f(atimberrington,aterenceharvey)).
pos(f(alorigalinski,abaa)).
pos(f(ametcalfestephen,cbcc)).
pos(f(aalexandrawinisky,abcb)).
pos(f(abba,abca)).
pos(f(abca,acca)).
pos(f(caaa,alloydalan)).
pos(f(aangelinasarova,ageorgistamatov)).
pos(f(asoderberghsteven,ascottcaan)).
pos(f(alylelovett,agretascacchi)).
pos(f(abcb,aarmelledeutsch)).
pos(f(amanueladolcemascolo,avannifois)).
pos(f(agrimaldiaurelioi,amaurolenares)).
pos(f(bbbc,bcbc)).
pos(f(bbab,aacb)).
pos(f(bccb,arenateschroeter)).
pos(f(apunchevborislav,alyubomirbachvarov)).
pos(f(ajustinmonjo,asharonstone)).
pos(f(abaa,aelliottgould)).
pos(f(afabiolobello,aacb)).
pos(f(aluciasardo,bcca)).
pos(f(ametcalfestephen,ajaimzwoolvett)).
pos(f(adannflorek,asheilapaterson)).
pos(f(atonetticlaudio,bcbc)).
pos(f(amiguelferrer,acaitlinoheaney)).
pos(f(ccbc,alucavitrano)).
pos(f(amarccaleb,cbbb)).
pos(f(agustemmanuelii,astevekalfa)).
pos(f(aantoniettacarbonetti,amaurolenares)).
pos(f(bbaa,abrigittefossey)).
pos(f(amarisaburger,amaxmller)).
pos(f(ajurneesmollett,aconnorwiddows)).
pos(f(acaitlinoheaney,agusmercurio)).
pos(f(aneilmaskell,asharonstone)).
pos(f(cccc,aalancpeterson)).
pos(f(amaxmller,akarinthaler)).
pos(f(avannifois,bacb)).
pos(f(adavidmorrissey,amarksangster)).
pos(f(avannifois,amanueladolcemascolo)).
pos(f(amanueladolcemascolo,aconsuelolupo)).
pos(f(aangelinasarova,ahristodinev)).
pos(f(bccb,azensmichael)).
pos(f(abac,anikoladadov)).
pos(f(amarcocavicchioli,aluciasardo)).
pos(f(aterenceharvey,aellenthomas)).
pos(f(amarcoleonardi,cbca)).
pos(f(abba,ajaimzwoolvett)).
pos(f(anevenakokanova,ajannowicki)).
pos(f(aacb,bcca)).
pos(f(aserenaautieri,accc)).
pos(f(aheathcotewilliams,aellenthomas)).
pos(f(asoderberghsteven,abaa)).
pos(f(abenjohnson,asharonstone)).
pos(f(atizianalodato,alucavitrano)).
pos(f(caab,awhoopigoldberg)).
pos(f(babc,agrimaldiaurelioi)).
pos(f(ahubertmulzer,cbaa)).
pos(f(agretascacchi,aaaa)).
pos(f(ajuttawachowiak,ajrggudzuhn)).
pos(f(aminianden,anelsonpeltz)).
pos(f(abrigittefossey,aloccorbery)).
pos(f(ajrggudzuhn,ccac)).
pos(f(aalancpeterson,acca)).
pos(f(ajuttawachowiak,aleonardlansink)).
pos(f(aterenceharvey,asharonstone)).
pos(f(abrigittefossey,apierrearditi)).
pos(f(babb,afloramontgomery)).
pos(f(akostatsonev,anevenakokanova)).
pos(f(aaab,aannamariagherardi)).
pos(f(aengelhardtwilhelm,ahorstkummeth)).
pos(f(astevekuhn,bcaa)).
pos(f(amarinovichanton,aivandimov)).
pos(f(adavidthewlis,acharlotterampling)).
pos(f(ahorstkummeth,ccbb)).
pos(f(aluciacammalleri,abiagiobarone)).
pos(f(astefanpetrov,aangelinasarova)).
pos(f(abenjohnson,cbab)).
pos(f(asheilapaterson,abenjohnson)).
pos(f(apatricejuiff,aestefanacastro)).
pos(f(akunkabaeva,atzvetolyubrakovski)).
pos(f(apetyasilyanova,apetardespotov)).
pos(f(cbab,abca)).
pos(f(aacb,asalvatorelazzaro)).
pos(f(aengelhardtwilhelm,amarkusbker)).
pos(f(afredward,awhoopigoldberg)).
pos(f(baca,aguillaumeromain)).
pos(f(abradpitt,aminianden)).
pos(f(atzvetolyubrakovski,amariashopova)).
pos(f(avyarakovacheva,aivantonev)).
pos(f(abradpitt,amarkgantt)).
pos(f(cccc,cbcc)).
pos(f(atimberrington,aneilmaskell)).
pos(f(aaca,bcca)).
pos(f(aacb,bbab)).
pos(f(ajurneesmollett,abillyconnolly)).
pos(f(ajuliaroberts,cabc)).
pos(f(adinaconnolly,aandygarcia)).
pos(f(amariashopova,astefanpejchev)).
pos(f(abradpitt,alorigalinski)).
pos(f(asharonstone,afrankcturner)).
pos(f(cabc,anelsonpeltz)).
pos(f(amanueladolcemascolo,abiagiobarone)).
pos(f(abrnicebejo,adidierdijoux)).
pos(f(acesareapolito,aeddasabatini)).
pos(f(alaurabetti,bcac)).
pos(f(apakulaalanj,astanleytucci)).
pos(f(aivanbratanov,akunkabaeva)).
pos(f(asheilapaterson,aianholm)).
pos(f(abruceayoung,achelcieross)).
pos(f(aulrichmhe,ccac)).
pos(f(anicolegrimaudo,aaab)).
pos(f(acaseyaffleck,aeddiejemison)).
pos(f(ajaimzwoolvett,cbab)).
pos(f(ccbb,amaxmller)).
pos(f(abcb,ajuliedray)).
pos(f(aaaa,acynthiastevenson)).
pos(f(atheresascholze,aleonardlansink)).
pos(f(acatonjonesmichael,adavidmorrissey)).
pos(f(amariashopova,aivanbratanov)).
pos(f(aannejacques,ajuliaroberts)).
pos(f(atheresascholze,avolkerranisch)).
pos(f(amariashopova,bbcb)).
pos(f(accilecassel,astevekalfa)).
pos(f(afrankpatton,abradpitt)).
pos(f(araffaeladavi,acbc)).
pos(f(baac,akarinthaler)).
pos(f(astancollymore,aellenthomas)).
pos(f(adanielegalea,alaurabetti)).
pos(f(acac,abiagiobarone)).
pos(f(adinaconnolly,ascottcaan)).
pos(f(aandreasschwaiger,arenateschroeter)).
pos(f(abbb,amarcoleonardi)).
pos(f(aaltmanroberti,abrionjames)).
pos(f(amaurizionicolosi,aluciasardo)).
pos(f(acba,amarcoleonardi)).
pos(f(ajurneesmollett,abca)).
pos(f(accc,baab)).
pos(f(aabc,aguillaumeromain)).
pos(f(aguillaumeromain,abrnicebejo)).
pos(f(abrionjames,awhoopigoldberg)).
pos(f(ahughkeaysbyrne,cbbb)).
pos(f(atimothypaulperez,ageorgeclooney)).
pos(f(avergnejeanpierre,bccc)).
pos(f(atraykovatanas,astoychomazgalov)).
pos(f(akarinthaler,baac)).
pos(f(aginachiarelli,aalancpeterson)).
pos(f(anikoladadov,akunkabaeva)).
pos(f(cabb,atonygoldwyn)).
pos(f(asurchadzhievstefani,aivankondov)).
pos(f(aklischstefan,baac)).
pos(f(adorothymalone,ageorgedzundza)).
pos(f(afrankpatton,ccca)).
pos(f(astevekalfa,afrancishuster)).
pos(f(acaitlinoheaney,ajustinmonjo)).
pos(f(azensmichael,adietermann)).
pos(f(bbca,aabb)).
pos(f(ccbb,amarkusbker)).
pos(f(astancollymore,asharonstone)).
pos(f(achelcieross,amichaeldouglas)).
pos(f(ccaa,abcc)).
pos(f(afrankcturner,aginachiarelli)).
pos(f(apieradegliesposti,bbab)).
pos(f(aedkross,acatherinezetajones)).
pos(f(cabc,aaac)).
pos(f(afrankcturner,cccc)).
pos(f(amichaeldouglas,asharonstone)).
pos(f(cbaa,aandreasschwaiger)).
pos(f(aserenaautieri,aconsuelolupo)).
pos(f(aangelahall,afredward)).
pos(f(anevenakokanova,alyubomirbachvarov)).
pos(f(ajuliaroberts,acatherinezetajones)).
pos(f(abca,asheilapaterson)).
pos(f(aclaudiamessner,ajrggudzuhn)).
pos(f(apaolaciampi,amarcoleonardi)).
pos(f(ageorgistamatov,akunkabaeva)).
pos(f(afrancomirabella,agiancarloscuderi)).
pos(f(akrgnther,agerdlohmeyer)).
pos(f(cbcc,cccc)).
pos(f(aluciasardo,abiagiobarone)).
pos(f(acaseyaffleck,acatherinezetajones)).
pos(f(bcbb,apunchevborislav)).
pos(f(babb,ajanchappell)).
pos(f(bbcb,avyarakovacheva)).
pos(f(akappesstphane,astevekalfa)).
pos(f(agutjahrrainer,ahubertmulzer)).
pos(f(amarcoleonardi,araffaeladavi)).
pos(f(bbaa,baca)).
pos(f(agrimaldiaurelioi,agiancarloscuderi)).
pos(f(abiagiobarone,aileanarigano)).
pos(f(bcba,adorothymalone)).
pos(f(abrionjames,acynthiastevenson)).
pos(f(aantoniettacarbonetti,avincenzocrivello)).
pos(f(astevekuhn,acaitlinoheaney)).
pos(f(ageorgedzundza,aleilanisarelle)).
pos(f(adannflorek,bbca)).
pos(f(alylelovett,aangelahall)).
pos(f(astephanbernhard,bccb)).
pos(f(aelliottgould,ascottcaan)).
pos(f(aileanarigano,acarmelogalati)).
pos(f(adavidarnett,asharonstone)).
pos(f(apaullnolan,abradpitt)).
pos(f(averhoevenpauli,amichaeldouglas)).
pos(f(astoychomazgalov,acab)).
pos(f(apieradegliesposti,amaurolenares)).
pos(f(amiguelferrer,bcaa)).
pos(f(aacb,abbc)).
pos(f(apaullnolan,bcab)).
pos(f(aceceliaannbirt,acbb)).
pos(f(atimothypaulperez,bcab)).
pos(f(astevekuhn,asharonstone)).
pos(f(akonstanzebreitebner,avolkerranisch)).
pos(f(aginachiarelli,aianholm)).
pos(f(acbb,amarkgantt)).
pos(f(cabb,ajamessikking)).
pos(f(agretascacchi,atimrobbins)).
pos(f(ccbb,baac)).
pos(f(baab,avannifois)).
pos(f(asydneypollack,awhoopigoldberg)).
pos(f(adebraengle,amarccaleb)).
pos(f(amichaeldouglas,ajeannetripplehorn)).
pos(f(asurchadzhievstefani,asavahashamov)).
pos(f(abarbaratabita,avannifois)).
pos(f(aandreasschwaiger,amarisaburger)).
pos(f(ajuliaroberts,aannejacques)).
pos(f(acab,asavahashamov)).
pos(f(acca,anormanarmour)).
pos(f(acarolflorence,ageorgeclooney)).
pos(f(aapprederisfranck,aloccorbery)).
pos(f(ajaimzwoolvett,cccc)).
pos(f(bcca,aantoniettacarbonetti)).
pos(f(abradpitt,cabc)).
pos(f(abraunbettinai,amarkusbker)).
pos(f(abba,abillyconnolly)).
pos(f(afloramontgomery,astancollymore)).
pos(f(aileanarigano,aconsuelolupo)).
pos(f(atzvetolyubrakovski,aangelinasarova)).
pos(f(alyubomirkanev,aalicjajachiewicz)).
pos(f(arobyndouglass,alloydalan)).
pos(f(ajuttawachowiak,bccb)).
pos(f(acesareapolito,cbca)).
pos(f(ajanchappell,cbbc)).
pos(f(araffaeladavi,bbba)).
pos(f(aangelahall,arichardegrant)).
pos(f(aangelinasarova,aganchoganchev)).
pos(f(aestefanacastro,aludwigbriand)).
pos(f(caac,agrimaldiaurelioi)).
pos(f(amaxmller,amarenschumacher)).
pos(f(asotirmaynolovski,cbac)).
pos(f(apunchevborislav,aemilmarkov)).
pos(f(acharlotterampling,aheathcotewilliams)).
pos(f(apieradegliesposti,amarcospicuglia)).
pos(f(agustemmanuelii,bcbc)).
pos(f(cabc,adontiffany)).
pos(f(aantoninobruschetta,aluciasardo)).
pos(f(amarisaburger,athomasstielner)).
pos(f(agrimaldiaurelioi,afabiolobello)).
pos(f(ccbc,cccb)).
pos(f(asheilapaterson,aconnorwiddows)).
pos(f(ajaimzwoolvett,ajurneesmollett)).
pos(f(bcbc,abonnetchristiani)).
pos(f(anicholaswoodeson,cabb)).
pos(f(abbb,acbc)).
pos(f(abbc,aacb)).
pos(f(abillcable,adorothymalone)).
pos(f(agrimaldiaurelioi,abbc)).
pos(f(averhoevenpauli,abenjaminmouton)).
pos(f(acbb,afrankpatton)).
pos(f(anevenakokanova,amichalbajor)).
pos(f(abogomilsimeonov,anevenakokanova)).
pos(f(astefanodionisi,apenlopecruz)).
pos(f(alewissmith,caaa)).
pos(f(aedkross,aminianden)).
pos(f(bcab,amarkgantt)).
pos(f(astevekalfa,ccab)).
pos(f(agrimaldiaurelioi,bcac)).
pos(f(adorothymalone,bcba)).
pos(f(baab,abiagiobarone)).
pos(f(aviktordanchenko,acab)).
pos(f(anicolegrimaudo,acorradofortuna)).
pos(f(bcbc,afranoisechristophe)).
pos(f(bacc,asoderberghsteven)).
pos(f(accb,cabb)).
pos(f(ajuliedray,avincentlecoeur)).
pos(f(alyubomirbobchevski,ccaa)).
pos(f(akunkabaeva,ageorgistamatov)).
pos(f(abac,aivantonev)).
pos(f(ajuttawachowiak,aulrichmhe)).
pos(f(adebraengle,agusmercurio)).
pos(f(baac,aengelhardtwilhelm)).
pos(f(afrancomirabella,bcca)).
pos(f(apetardespotov,anevenakokanova)).
pos(f(aleilanisarelle,ageorgedzundza)).
pos(f(bbab,aluciasardo)).
pos(f(babc,cbca)).
pos(f(aalancpeterson,cccc)).
pos(f(adinaconnolly,ageorgeclooney)).
pos(f(aconsuelolupo,aileanarigano)).
pos(f(afabiolobello,apieradegliesposti)).
pos(f(alloydalan,bcaa)).
pos(f(ageorgeclooney,afrankpatton)).
pos(f(amarksangster,cbbc)).
pos(f(aalicjajachiewicz,alyubomirkanev)).
pos(f(avyarakovacheva,aivandimov)).
pos(f(aaba,amarksangster)).
pos(f(astoychomazgalov,anevenakokanova)).
pos(f(aenzodimartino,aacb)).
pos(f(cbaa,amaxmller)).
pos(f(cbca,baaa)).
pos(f(ccba,aapprederisfranck)).
pos(f(asciveresmarianna,acarmelogalati)).
pos(f(alewissmith,acaitlinoheaney)).
pos(f(asheilapaterson,anormanarmour)).
pos(f(asharonstone,astancollymore)).
pos(f(bccb,agesinecukrowski)).
pos(f(amariashopova,astefanpetrov)).
pos(f(aberniemac,ageorgeclooney)).
pos(f(ametcalfestephen,abillyconnolly)).
pos(f(amariashopova,aivantonev)).
pos(f(bbaa,aapprederisfranck)).
pos(f(ccbb,athomasstielner)).
pos(f(amaurizionicolosi,aaca)).
pos(f(ajuliedray,aloccorbery)).
pos(f(aeddiejemison,acaseyaffleck)).
pos(f(alucavitrano,aradarassimov)).
pos(f(bbca,abillyconnolly)).
pos(f(aterenceharvey,afloramontgomery)).
pos(f(amariashopova,aganchoganchev)).
pos(f(amarksangster,aindiravarma)).
pos(f(bacc,aelliottgould)).
pos(f(agrimaldiaurelioi,babc)).
pos(f(ahristodinev,aangelinasarova)).
pos(f(asheilapaterson,abca)).
pos(f(asydneypollack,aleahayres)).
pos(f(acatherinezetajones,abradpitt)).
pos(f(agiancarloscuderi,apieradegliesposti)).
pos(f(akostatsonev,cbac)).
pos(f(akronthalerthomas,ahubertmulzer)).
pos(f(ajrggudzuhn,arenateschroeter)).
pos(f(aconnorwiddows,cccc)).
pos(f(aaba,aellenthomas)).
pos(f(bbca,adillonmoen)).
pos(f(abaa,acarolflorence)).
pos(f(alaurabetti,amarcoleonardi)).
pos(f(apaolaciampi,adanielegalea)).
pos(f(bacc,alorigalinski)).
pos(f(aconsuelolupo,bacb)).
pos(f(amillergeorgei,ajustinmonjo)).
pos(f(asaromiano,apieradegliesposti)).
pos(f(ageorgeclooney,adinaconnolly)).
pos(f(apakulaalanj,atonygoldwyn)).
pos(f(acaa,cbac)).
pos(f(bcbc,asummereric)).
pos(f(ajaimzwoolvett,acca)).
pos(f(aleahayres,aaaa)).
pos(f(aginachiarelli,afrankcturner)).
pos(f(aabb,cccc)).
pos(f(aaca,asaromiano)).
pos(f(baaa,alaurabetti)).
pos(f(ageorgeclooney,cabc)).
pos(f(aeddiejemison,acbb)).
pos(f(ajohnfinn,cabb)).
pos(f(abrnicebejo,aludwigbriand)).
pos(f(cabb,astanleyanderson)).
pos(f(astevekalfa,accilecassel)).
pos(f(arichardegrant,acynthiastevenson)).
pos(f(asharonstone,babb)).
pos(f(ajrggudzuhn,atheresascholze)).
pos(f(ahughkeaysbyrne,bcaa)).
pos(f(asurchadzhievstefani,aviktordanchenko)).
pos(f(astephentobolowsky,adorothymalone)).
pos(f(cabb,astanleytucci)).
pos(f(ajeannetripplehorn,awayneknight)).
pos(f(ahristodinev,ccaa)).
pos(f(atzvetolyubrakovski,akunkabaeva)).
pos(f(aandygarcia,aminianden)).
pos(f(aaab,abattiatofranco)).
pos(f(bbac,anevenakokanova)).
pos(f(ahubertmulzer,ccbb)).
pos(f(araffaeladavi,astefanodionisi)).
pos(f(acaa,apunchevborislav)).
pos(f(adavidarnett,adebraengle)).
pos(f(ajanchappell,adavidmorrissey)).
pos(f(agretascacchi,caab)).
pos(f(aconnorwiddows,asheilapaterson)).
pos(f(cccc,ajaimzwoolvett)).
pos(f(ajeannetripplehorn,abillcable)).
pos(f(abca,cccc)).
pos(f(bcbb,cbac)).
pos(f(acba,bcac)).
pos(f(alarrysontag,adinaconnolly)).
pos(f(alyubomirbobchevski,acab)).
pos(f(achelcieross,ajackmcgee)).
pos(f(ageorgistamatov,aangelinasarova)).
pos(f(agrimaldiaurelioi,asaromiano)).
pos(f(adavidarnett,acaitlinoheaney)).
pos(f(bcab,afrankpatton)).
pos(f(aaltmanroberti,alylelovett)).
pos(f(ascottcaan,aminianden)).
pos(f(apieradegliesposti,avincenzocrivello)).
pos(f(cbbc,amarksangster)).
pos(f(bbba,acba)).
pos(f(abenjaminmouton,asharonstone)).
pos(f(acbb,apaullnolan)).
pos(f(acoralyzahonero,astevekalfa)).
pos(f(anikoladadov,abac)).
pos(f(bcab,ajorgerhernandez)).
pos(f(asamantharnier,bccc)).
pos(f(asaromiano,aacb)).
pos(f(asoderberghsteven,ajuliaroberts)).
pos(f(agesinecukrowski,bccb)).
pos(f(cbcc,ametcalfestephen)).
pos(f(apakulaalanj,anicholaswoodeson)).
pos(f(agiancarloscuderi,aantoniettacarbonetti)).
pos(f(ajaimzwoolvett,asharonstone)).
pos(f(agutjahrrainer,agerdlohmeyer)).
pos(f(cbac,bbac)).
pos(f(astefanpejchev,abac)).
pos(f(bacb,avannifois)).
pos(f(adidierdijoux,abrigittefossey)).
pos(f(acbc,abbb)).
pos(f(aangelinasarova,amikhailmikhajlov)).
pos(f(aaltmanroberti,asydneypollack)).
pos(f(baca,ccba)).
pos(f(acarmelogalati,amanueladolcemascolo)).
pos(f(akrgnther,athomasstielner)).
pos(f(ajuliedray,adidierdijoux)).
pos(f(akrgnther,amaxmller)).
pos(f(aabb,bbca)).
pos(f(agusmercurio,acaitlinoheaney)).
pos(f(abca,cbab)).
pos(f(asheilapaterson,abillyconnolly)).
pos(f(apetyasilyanova,astoychomazgalov)).
pos(f(ajohnlithgow,cabb)).
pos(f(aangelinasarova,alyubomirbobchevski)).
pos(f(alucavitrano,atizianalodato)).
pos(f(ageorgeclooney,apaullnolan)).
pos(f(abrionjames,agretascacchi)).
pos(f(avincentdonofrio,adinamerrill)).
pos(f(akronthalerthomas,agerdlohmeyer)).
pos(f(bcac,aeddasabatini)).
pos(f(cbca,acesareapolito)).
pos(f(aabb,cbab)).
pos(f(cccb,adonatellafinocchiaro)).
pos(f(aedkross,aannejacques)).
pos(f(ccac,aleonardlansink)).
pos(f(abaa,asoderberghsteven)).
pos(f(cabb,bbcc)).
pos(f(asoderberghsteven,aandygarcia)).
pos(f(adannflorek,aginachiarelli)).
pos(f(aemilmarkov,cbac)).
pos(f(aconsuelolupo,amanueladolcemascolo)).
pos(f(amaurizionicolosi,aantoniettacarbonetti)).
pos(f(ajuliaroberts,cabb)).
pos(f(caba,aarmelledeutsch)).
pos(f(akunkabaeva,aivanbratanov)).
pos(f(amarksangster,babb)).
pos(f(caab,aaltmanroberti)).
pos(f(abcb,avergnejeanpierre)).
pos(f(akonstanzebreitebner,aulrichmhe)).
pos(f(aaca,abbc)).
pos(f(amariashopova,aacc)).
pos(f(ajeannetripplehorn,adanielvonbargen)).
pos(f(aluciasardo,accc)).
pos(f(asoderberghsteven,adavidsontag)).
pos(f(cbac,acaa)).
pos(f(adebraengle,ajustinmonjo)).
pos(f(atommikulla,akarinthaler)).
pos(f(aileanarigano,avannifois)).
pos(f(ajanchappell,adavidthewlis)).
pos(f(cbba,achelcieross)).
pos(f(aindiravarma,asharonstone)).
pos(f(aaac,adinaconnolly)).
pos(f(amarisaburger,ahubertmulzer)).
pos(f(aacc,avyarakovacheva)).
pos(f(adanielegalea,apenlopecruz)).
pos(f(aandygarcia,acatherinezetajones)).
pos(f(aivanbratanov,avyarakovacheva)).
pos(f(afloramontgomery,cbbc)).
pos(f(adimitarhadzhiyanev,apetyasilyanova)).
pos(f(aclaudiamessner,avolkerranisch)).
pos(f(acaitlinoheaney,amiguelferrer)).
pos(f(amarkgantt,abaa)).
pos(f(ahughdancy,ajanchappell)).
pos(f(abaa,afrankpatton)).
pos(f(amarkgantt,acbb)).
pos(f(aengelhardtwilhelm,agerdlohmeyer)).
pos(f(avincentlecoeur,aarmelledeutsch)).
pos(f(aandreasschwaiger,agesinecukrowski)).
pos(f(aantoniettacarbonetti,amarcospicuglia)).
pos(f(ajuliedray,bccc)).
pos(f(amarenschumacher,athomasstielner)).
pos(f(abrionjames,aangelahall)).
pos(f(aellenthomas,ahughdancy)).
pos(f(caaa,astevekuhn)).
pos(f(abillyconnolly,acca)).
pos(f(adinaconnolly,aedkross)).
pos(f(ajackmcgee,achelcieross)).
pos(f(aelliottgould,ccca)).
pos(f(alarrysontag,cabc)).
pos(f(ccaa,cbcb)).
pos(f(caba,abrnicebejo)).
pos(f(cbac,alyubomirbachvarov)).
pos(f(astephentobolowsky,achelcieross)).
pos(f(asonyadjulgerova,apetardespotov)).
pos(f(asciveresmarianna,avannifois)).
pos(f(azensmichael,aandreasschwaiger)).
pos(f(abiagiobarone,aluciasardo)).
pos(f(ageorgeclooney,aeddiejemison)).
pos(f(atraykovatanas,aivangrigorov)).
pos(f(aangelinasarova,aivanbratanov)).
pos(f(aaab,anicolegrimaudo)).
pos(f(avergnejeanpierre,aloccorbery)).
pos(f(arobyndouglass,adavidarnett)).
pos(f(afrankpatton,acbb)).
pos(f(asharonstone,adannflorek)).
pos(f(aguillaumeromain,aalexandrawinisky)).
pos(f(amanueladolcemascolo,accc)).
pos(f(aelliottgould,acaseyaffleck)).
pos(f(aacb,asaromiano)).
pos(f(avincenzocrivello,afrancomirabella)).
pos(f(awhoopigoldberg,arichardegrant)).
pos(f(ajustinmonjo,arobyndouglass)).
pos(f(bacc,ajorgerhernandez)).
pos(f(afrancomirabella,abbc)).
pos(f(amarcocavicchioli,afrancomirabella)).
pos(f(adavidarnett,arobyndouglass)).
pos(f(acynthiastevenson,alylelovett)).
pos(f(bbca,aalancpeterson)).
pos(f(abogomilsimeonov,cbac)).
pos(f(bcca,aacb)).
pos(f(achelcieross,adanielvonbargen)).
pos(f(acbb,alorigalinski)).
pos(f(akrgnther,baac)).
pos(f(asoderberghsteven,abradpitt)).
pos(f(ajrggudzuhn,aclaudiamessner)).
pos(f(asheilapaterson,cbcc)).
pos(f(ajorgerhernandez,acaseyaffleck)).
pos(f(adanielvonbargen,achelcieross)).
pos(f(alyubomirkanev,cbac)).
pos(f(bbba,aeddasabatini)).
pos(f(asoderberghsteven,acbb)).
pos(f(acarolflorence,ccca)).
pos(f(amarcocavicchioli,aantoniettacarbonetti)).
pos(f(cbbb,astevekuhn)).
pos(f(aaab,atizianalodato)).
pos(f(agrimaldiaurelioi,amaurizionicolosi)).
pos(f(alorigalinski,acbb)).
pos(f(aginachiarelli,ajaimzwoolvett)).
pos(f(agretascacchi,avincentdonofrio)).
pos(f(aconnorwiddows,cbab)).
pos(f(aestefanacastro,adidierdijoux)).
pos(f(astephanbernhard,aandreasschwaiger)).
pos(f(cabc,alarrysontag)).
pos(f(caaa,alewissmith)).
pos(f(aantoniettacarbonetti,abbc)).
pos(f(cabb,anicholaswoodeson)).
pos(f(avolkerranisch,ajuttawachowiak)).
pos(f(asoderberghsteven,ccca)).
pos(f(adanielegalea,apaolaciampi)).
pos(f(astefanodionisi,abab)).
pos(f(abradpitt,acatherinezetajones)).
pos(f(asharonstone,abillcable)).
pos(f(cccc,aianholm)).
pos(f(adidierdijoux,aestefanacastro)).
pos(f(apierrearditi,baca)).
pos(f(avergnejeanpierre,abcb)).
pos(f(alorigalinski,acaseyaffleck)).
pos(f(abradpitt,aelliottgould)).
pos(f(aangelahall,apetergallagher)).
pos(f(acatherinezetajones,anelsonpeltz)).
pos(f(baac,akronthalerthomas)).
pos(f(adanielegalea,abab)).
pos(f(apaullnolan,ascottcaan)).
pos(f(baac,amarisaburger)).
pos(f(asamantharnier,adidierdijoux)).
pos(f(abraunbettinai,ahubertmulzer)).
pos(f(asurchadzhievstefani,astoychomazgalov)).
pos(f(agesinecukrowski,aulrichmhe)).
pos(f(amarinovichanton,astefanpejchev)).
pos(f(acca,adillonmoen)).
pos(f(cabc,ageorgeclooney)).
pos(f(amarisaburger,agerdlohmeyer)).
pos(f(apieradegliesposti,bcca)).
pos(f(adillonmoen,cbab)).
pos(f(abcb,aalexandrawinisky)).
pos(f(alorigalinski,ccca)).
pos(f(ajeannetripplehorn,amichaeldouglas)).
pos(f(adinamerrill,alylelovett)).
pos(f(averhoevenpauli,ajackmcgee)).
pos(f(aradarassimov,aantoninobruschetta)).
pos(f(cbac,asotirmaynolovski)).
pos(f(atzvetolyubrakovski,avyarakovacheva)).
pos(f(aconsuelolupo,aserenaautieri)).
pos(f(aaab,ccbc)).
pos(f(abab,baaa)).
pos(f(adannflorek,abba)).
pos(f(atimothypaulperez,acaseyaffleck)).
pos(f(bbab,agrimaldiaurelioi)).
pos(f(akarinthaler,ahorstkummeth)).
pos(f(bbcb,amariashopova)).
pos(f(alyubomirbachvarov,anevenakokanova)).
pos(f(aindiravarma,acharlotterampling)).
pos(f(acaseyaffleck,aannejacques)).
pos(f(cbbc,acatonjonesmichael)).
pos(f(astephanbernhard,ajrggudzuhn)).
pos(f(agiancarloscuderi,afrancomirabella)).
pos(f(aannamariagherardi,alucavitrano)).
pos(f(aenzodimartino,apieradegliesposti)).
pos(f(cbcc,asheilapaterson)).
pos(f(baaa,agrimaldiaurelioi)).
pos(f(cbcb,aangelinasarova)).
pos(f(abca,bbca)).
pos(f(amarisaburger,baac)).
pos(f(babb,asharonstone)).
pos(f(ajorgerhernandez,bcab)).
pos(f(bbca,abenjohnson)).
pos(f(ascottcaan,alorigalinski)).
pos(f(aconnorwiddows,aginachiarelli)).
pos(f(aminianden,abradpitt)).
pos(f(abraunbettinai,amaxmller)).
pos(f(astevekuhn,adebraengle)).
pos(f(asonyadjulgerova,aivangrigorov)).
pos(f(babb,atimberrington)).
pos(f(apaolaciampi,acbc)).
pos(f(aabc,bbaa)).
pos(f(adanielegalea,cbca)).
pos(f(ccca,apaullnolan)).
pos(f(akappesstphane,bcbc)).
pos(f(avincenzocrivello,aacb)).
pos(f(abenjaminmouton,aleilanisarelle)).
pos(f(acbc,cbca)).
pos(f(acarmelogalati,aileanarigano)).
pos(f(abenjaminmouton,adorothymalone)).
pos(f(astephanbernhard,avolkerranisch)).
pos(f(amaxmller,ccbb)).
pos(f(atimrobbins,adinamerrill)).
pos(f(acaa,anevenakokanova)).
pos(f(astefanpetrov,abac)).
pos(f(bcca,aluciasardo)).
pos(f(aalancpeterson,asheilapaterson)).
pos(f(anevenakokanova,astoychomazgalov)).
pos(f(atheresascholze,aandreasschwaiger)).
pos(f(bbcb,abac)).
pos(f(asheilapaterson,aalancpeterson)).
pos(f(ccca,amarkgantt)).
pos(f(cbca,amarcoleonardi)).
pos(f(akinkelmartin,ahorstkummeth)).
pos(f(aindiravarma,amarksangster)).
pos(f(adebraengle,ahughkeaysbyrne)).
pos(f(asharonstone,adillonmoen)).
pos(f(aangelinasarova,bbcb)).
pos(f(bacc,afrankpatton)).
pos(f(apatricejuiff,baca)).
pos(f(asonyadjulgerova,adimitarhadzhiyanev)).
pos(f(cbac,amichalbajor)).
pos(f(aviktordanchenko,ccaa)).
pos(f(aberniemac,ascottcaan)).
pos(f(aceceliaannbirt,bcab)).
pos(f(azensmichael,avolkerranisch)).
pos(f(amanueladolcemascolo,acarmelogalati)).
pos(f(cabb,ajohnlithgow)).
pos(f(aabb,asharonstone)).
pos(f(bcbc,akappesstphane)).
pos(f(amanliosgalambro,atizianalodato)).
pos(f(avyarakovacheva,astefanpejchev)).
pos(f(anelsonpeltz,aminianden)).
pos(f(afrancishuster,bcbc)).
pos(f(aaca,amaurizionicolosi)).
pos(f(aandreasschwaiger,akarinthaler)).
pos(f(abarbaratabita,abiagiobarone)).
pos(f(adontiffany,acatherinezetajones)).
pos(f(cabb,accb)).
pos(f(asotirmaynolovski,anevenakokanova)).
pos(f(aaca,caac)).
pos(f(amillergeorgei,astevekuhn)).
pos(f(adonatellafinocchiaro,amanliosgalambro)).
pos(f(asamantharnier,caba)).
pos(f(cbab,abillyconnolly)).
pos(f(aaltmanroberti,avincentdonofrio)).
pos(f(amarenschumacher,amarkusbker)).
pos(f(acarmelogalati,bacb)).
pos(f(abradpitt,aceceliaannbirt)).
pos(f(asaromiano,aaca)).
pos(f(amarksangster,aneilmaskell)).
pos(f(asciveresmarianna,aconsuelolupo)).
pos(f(amarkgantt,ccca)).
pos(f(caca,abradpitt)).
pos(f(astanleytucci,cabb)).
pos(f(adinamerrill,abrionjames)).
pos(f(amarenschumacher,ahubertmulzer)).
pos(f(asharonstone,adavidarnett)).
pos(f(babb,acatonjonesmichael)).
pos(f(cbaa,athomasstielner)).
pos(f(cccc,abenjohnson)).
pos(f(abarbaratabita,acarmelogalati)).
pos(f(cbbc,ajanchappell)).
pos(f(ccba,aabc)).
pos(f(cccc,abillyconnolly)).
pos(f(acaitlinoheaney,adavidarnett)).
pos(f(amillergeorgei,adavidarnett)).
pos(f(apatricejuiff,abrigittefossey)).
pos(f(afrancomirabella,amaurolenares)).
pos(f(ajuliedray,aguillaumeromain)).
pos(f(aapprederisfranck,caba)).
pos(f(alewissmith,adebraengle)).
pos(f(agrimaldiaurelioi,amarcocavicchioli)).
pos(f(afrankpatton,acaseyaffleck)).
pos(f(afrankpatton,bacc)).
pos(f(ajorgerhernandez,abaa)).
pos(f(aconsuelolupo,aluciasardo)).
pos(f(aaca,bbab)).
pos(f(amillergeorgei,amarccaleb)).
pos(f(abba,aconnorwiddows)).
pos(f(abradpitt,aberniemac)).
pos(f(awhoopigoldberg,apetergallagher)).
pos(f(aalancpeterson,bbca)).
pos(f(ccaa,asavahashamov)).
pos(f(abruceayoung,ajeannetripplehorn)).
pos(f(aangelahall,abrionjames)).
pos(f(averhoevenpauli,astephentobolowsky)).
pos(f(aandreasschwaiger,ccbb)).
pos(f(aluciacammalleri,avannifois)).
pos(f(aabb,abba)).
pos(f(cabc,abradpitt)).
pos(f(bcab,aceceliaannbirt)).
pos(f(aantoniettacarbonetti,amarcocavicchioli)).
pos(f(aneilmaskell,atimberrington)).
pos(f(abruceayoung,adorothymalone)).
pos(f(agutjahrrainer,amarkusbker)).
pos(f(aandygarcia,adinaconnolly)).
pos(f(aleonardlansink,arenateschroeter)).
pos(f(aluciasardo,afabiolobello)).
pos(f(acca,aabb)).
pos(f(aleonardlansink,aclaudiamessner)).
pos(f(agrimaldiaurelioi,adanielegalea)).
pos(f(ajurneesmollett,afrankcturner)).
pos(f(astoychomazgalov,aalicjajachiewicz)).
pos(f(astephentobolowsky,aleilanisarelle)).
pos(f(ahubertmulzer,akarinthaler)).
pos(f(aeddiejemison,ageorgeclooney)).
pos(f(cbca,bcac)).
pos(f(aluciasardo,asalvatorelazzaro)).
pos(f(aludwigbriand,aalexandrawinisky)).
pos(f(bbbb,acynthiastevenson)).
pos(f(ascottcaan,amarkgantt)).
pos(f(acaseyaffleck,aminianden)).
pos(f(afrancomirabella,bbab)).
pos(f(bcca,afrancomirabella)).
pos(f(aleahayres,avincentdonofrio)).
pos(f(avyarakovacheva,bbcb)).
pos(f(aianholm,aginachiarelli)).
pos(f(ajustinmonjo,caaa)).
pos(f(akarinthaler,amaxmller)).
pos(f(alarrysontag,aannejacques)).
pos(f(apunchevborislav,astoychomazgalov)).
pos(f(aneilmaskell,ajanchappell)).
pos(f(anormanarmour,ajurneesmollett)).
pos(f(afranoisechristophe,bcbc)).
pos(f(asharonstone,ajackmcgee)).
pos(f(akronthalerthomas,ahorstkummeth)).
pos(f(aindiravarma,ajanchappell)).
pos(f(adorothymalone,abruceayoung)).
pos(f(atimrobbins,acynthiastevenson)).
pos(f(aannamariagherardi,aantoninobruschetta)).
pos(f(ascottcaan,caca)).
pos(f(ajuliedray,caba)).
pos(f(akunkabaeva,aivandimov)).
pos(f(adeanstockwell,acynthiastevenson)).
pos(f(aalancpeterson,abba)).
pos(f(aluciasardo,aantoninobruschetta)).
pos(f(aberniemac,acbb)).
pos(f(abrnicebejo,bbaa)).
pos(f(anevenakokanova,bbac)).
pos(f(akinkelmartin,ahubertmulzer)).
pos(f(acatonjonesmichael,aheathcotewilliams)).
pos(f(baca,avincentlecoeur)).
pos(f(aannejacques,aedkross)).
pos(f(abattiatofranco,cccb)).
pos(f(ajanchappell,ahughdancy)).
pos(f(astevekuhn,caaa)).
pos(f(aacb,agiancarloscuderi)).
pos(f(adonatellafinocchiaro,cccb)).
pos(f(adidierdijoux,baca)).
pos(f(cacc,bcbc)).
pos(f(akunkabaeva,anikoladadov)).
pos(f(akinkelmartin,agerdlohmeyer)).
pos(f(alorigalinski,abradpitt)).
pos(f(abrigittefossey,bccc)).
pos(f(aterenceharvey,amarksangster)).
pos(f(aludwigbriand,abrigittefossey)).
pos(f(astefanpejchev,akunkabaeva)).
pos(f(apierrearditi,aabc)).
pos(f(avannifois,aserenaautieri)).
pos(f(aangelinasarova,astoychomazgalov)).
pos(f(aluciasardo,acarmelogalati)).
pos(f(aklischstefan,atommikulla)).
pos(f(amarinovichanton,aganchoganchev)).
pos(f(bbbb,aangelahall)).
pos(f(atonygoldwyn,cabb)).
pos(f(adonatellafinocchiaro,aantoninobruschetta)).
pos(f(avergnejeanpierre,bbaa)).
pos(f(cabc,acaseyaffleck)).
pos(f(amillergeorgei,alloydalan)).
pos(f(abillcable,aleilanisarelle)).
pos(f(aaac,asoderberghsteven)).
pos(f(bbaa,aabc)).
pos(f(asoderberghsteven,acaseyaffleck)).
pos(f(awilliamatherton,cabb)).
pos(f(ajurneesmollett,aalancpeterson)).
pos(f(atzenokandov,aangelinasarova)).
pos(f(amarksangster,adavidmorrissey)).
pos(f(acorradofortuna,ccbc)).
pos(f(aalexandrawinisky,aludwigbriand)).
pos(f(abba,abenjohnson)).
pos(f(averhoevenpauli,cbba)).
pos(f(asharonstone,astevekuhn)).
pos(f(ametcalfestephen,adannflorek)).
pos(f(astefanpetrov,amariashopova)).
pos(f(bbaa,ajuliedray)).
pos(f(ajuliedray,ccba)).
pos(f(adorothymalone,adanielvonbargen)).
pos(f(adavidmorrissey,ajanchappell)).
pos(f(bbaa,abrnicebejo)).
pos(f(afrancomirabella,asaromiano)).
pos(f(araffaeladavi,amarcoleonardi)).
pos(f(abradpitt,caca)).
pos(f(cabb,ajohnheard)).
pos(f(ahorstkummeth,amarisaburger)).
pos(f(aconnorwiddows,asharonstone)).
pos(f(aemiliaradeva,adimitarhadzhiyanev)).
pos(f(aestefanacastro,aguillaumeromain)).
pos(f(acynthiastevenson,apetergallagher)).
pos(f(acab,aivankondov)).
pos(f(agrimaldiaurelioi,amarcospicuglia)).
pos(f(acatherinezetajones,adavidsontag)).
pos(f(acaitlinoheaney,alewissmith)).
pos(f(aleahayres,alylelovett)).
pos(f(aandygarcia,cabc)).
pos(f(avincenzocrivello,aantoniettacarbonetti)).
pos(f(aklischstefan,ahorstkummeth)).
pos(f(amarenschumacher,agerdlohmeyer)).
pos(f(adinaconnolly,anelsonpeltz)).
pos(f(acaitlinoheaney,astevekuhn)).
pos(f(agesinecukrowski,aandreasschwaiger)).
pos(f(akunkabaeva,aganchoganchev)).
pos(f(abbc,agrimaldiaurelioi)).
pos(f(avannifois,aileanarigano)).
pos(f(ametcalfestephen,aianholm)).
pos(f(abattiatofranco,amanliosgalambro)).
pos(f(adanielvonbargen,adorothymalone)).
pos(f(asalvatorelazzaro,aacb)).
pos(f(aellenthomas,aaba)).
pos(f(akinkelmartin,amarkusbker)).
pos(f(asalvatorelazzaro,aluciasardo)).
pos(f(ccba,aalexandrawinisky)).
pos(f(apakulaalanj,awilliamatherton)).
pos(f(abaa,caca)).
pos(f(afrancomirabella,caac)).
pos(f(atommikulla,cbaa)).
pos(f(aivankondov,aangelinasarova)).
pos(f(aminianden,aaac)).
pos(f(akinkelmartin,aandreasschwaiger)).
pos(f(cbbb,adavidarnett)).
pos(f(ccca,aelliottgould)).
pos(f(aannejacques,alarrysontag)).
pos(f(aklischstefan,athomasstielner)).
pos(f(aaca,asalvatorelazzaro)).
pos(f(athomasstielner,amarisaburger)).
pos(f(apieradegliesposti,abbc)).
pos(f(aannamariagherardi,aaab)).
pos(f(astevekalfa,cacc)).
pos(f(adidierdijoux,aalexandrawinisky)).
pos(f(ahughdancy,atimberrington)).
pos(f(ccaa,aivankondov)).
pos(f(abaa,apaullnolan)).
pos(f(adeanstockwell,awhoopigoldberg)).
pos(f(aulrichmhe,akonstanzebreitebner)).
pos(f(adanielvonbargen,ajeannetripplehorn)).
pos(f(asaromiano,aantoniettacarbonetti)).
pos(f(agilbellows,ajurneesmollett)).
pos(f(avyarakovacheva,astefanpetrov)).
pos(f(bcab,caca)).
pos(f(asamantharnier,aloccorbery)).
pos(f(afirminerichard,astevekalfa)).
pos(f(cbab,afrankcturner)).
pos(f(awhoopigoldberg,bbbb)).
pos(f(abrigittefossey,apatricejuiff)).
pos(f(aengelhardtwilhelm,atommikulla)).
pos(f(acca,afrankcturner)).
pos(f(astancollymore,acharlotterampling)).
pos(f(cccc,agilbellows)).
pos(f(aromeclaudemichel,astevekalfa)).
pos(f(asharonstone,agilbellows)).
pos(f(bbcb,amarinovichanton)).
pos(f(amarkgantt,ascottcaan)).
pos(f(bcaa,amarccaleb)).
pos(f(amarkgantt,bacc)).
pos(f(amarcocavicchioli,aaca)).
pos(f(astephanbernhard,aleonardlansink)).
pos(f(apakulaalanj,ajohnlithgow)).
pos(f(avannifois,acac)).
pos(f(atimrobbins,agretascacchi)).
pos(f(afredward,acynthiastevenson)).
pos(f(acesareapolito,apaolaciampi)).
pos(f(aluciasardo,acorradofortuna)).
pos(f(cbac,abogomilsimeonov)).
pos(f(apetergallagher,acynthiastevenson)).
pos(f(ccab,astevekalfa)).
pos(f(baca,apierrearditi)).
pos(f(aellenthomas,adavidthewlis)).
pos(f(acbb,aelliottgould)).
pos(f(aalexandrawinisky,aloccorbery)).
pos(f(adavidthewlis,aellenthomas)).
pos(f(abrigittefossey,abcb)).
pos(f(apenlopecruz,astefanodionisi)).
pos(f(agusmercurio,caaa)).
pos(f(avincentdonofrio,acynthiastevenson)).
pos(f(arichardegrant,aleahayres)).
pos(f(baca,apatricejuiff)).
pos(f(alucavitrano,agabrieleferzetti)).
pos(f(babc,aeddasabatini)).
pos(f(asoderberghsteven,ageorgeclooney)).
pos(f(baac,aklischstefan)).
pos(f(abcb,aestefanacastro)).
pos(f(aladogedominique,astevekalfa)).
pos(f(acarolflorence,ascottcaan)).
pos(f(aulrichmhe,agesinecukrowski)).
pos(f(agretascacchi,afredward)).
pos(f(aluciasardo,amaurolenares)).
pos(f(accc,aluciasardo)).
pos(f(amichaeldouglas,adorothymalone)).
pos(f(afrancomirabella,asalvatorelazzaro)).
pos(f(ccaa,akirilyanev)).
pos(f(abrnicebejo,aguillaumeromain)).
pos(f(astephanbernhard,aulrichmhe)).
pos(f(aivangrigorov,apetyasilyanova)).
pos(f(bccc,abrigittefossey)).
pos(f(aileanarigano,abiagiobarone)).
pos(f(adillonmoen,abba)).
pos(f(apenlopecruz,adanielegalea)).
pos(f(amarcoleonardi,apenlopecruz)).
pos(f(akonstanzebreitebner,bccb)).
pos(f(amillergeorgei,ahughkeaysbyrne)).
pos(f(amaurizionicolosi,apieradegliesposti)).
pos(f(acca,cbcc)).
pos(f(aangelahall,bbbb)).
pos(f(akonstanzebreitebner,ajrggudzuhn)).
pos(f(aeddiejemison,ccca)).
pos(f(cbbc,acharlotterampling)).
pos(f(adinaconnolly,alarrysontag)).
pos(f(aindiravarma,afloramontgomery)).
pos(f(avyarakovacheva,aacc)).
pos(f(avincentlecoeur,abrigittefossey)).
pos(f(amarccaleb,bcaa)).
pos(f(aellenthomas,astancollymore)).
pos(f(cccc,abca)).
pos(f(aaba,atimberrington)).
pos(f(abraunbettinai,aandreasschwaiger)).
pos(f(abenjohnson,bbca)).
pos(f(bbaa,aestefanacastro)).
pos(f(astefanodionisi,cbca)).
pos(f(aianholm,cbab)).
pos(f(aannejacques,aaac)).
pos(f(aconnorwiddows,ajurneesmollett)).
pos(f(cacc,astevekalfa)).
pos(f(amarcoleonardi,abbb)).
pos(f(amaxmller,cbaa)).
pos(f(aacb,caac)).
pos(f(acbc,apaolaciampi)).
pos(f(abba,adannflorek)).
pos(f(acab,akirilyanev)).
pos(f(asharonstone,ahughdancy)).
pos(f(abba,cbcc)).
pos(f(aaba,acatonjonesmichael)).
pos(f(acab,ahristodinev)).
pos(f(abraunbettinai,athomasstielner)).
pos(f(bacb,accc)).
pos(f(adillonmoen,cccc)).
pos(f(anormanarmour,acca)).
pos(f(abcb,baca)).
pos(f(aauroraquattrocchi,astefanodionisi)).
pos(f(aeddiejemison,bacc)).
pos(f(akrgnther,amarkusbker)).
pos(f(aellenthomas,aheathcotewilliams)).
pos(f(ccca,ajorgerhernandez)).
pos(f(aengelhardtwilhelm,ahubertmulzer)).
pos(f(ajanchappell,aheathcotewilliams)).
pos(f(avergnejeanpierre,caba)).
pos(f(ccca,afrankpatton)).
pos(f(acca,adannflorek)).
pos(f(apaullnolan,ccca)).
pos(f(agilbellows,abba)).
pos(f(caba,aestefanacastro)).
pos(f(aclaudiamessner,aulrichmhe)).
pos(f(aconsuelolupo,acac)).
pos(f(abcc,ccaa)).
pos(f(aivankondov,acab)).
pos(f(asharonstone,aheathcotewilliams)).
pos(f(abbb,baaa)).
pos(f(cacb,aannejacques)).
pos(f(aloccorbery,aalexandrawinisky)).
pos(f(aleonardlansink,ajuttawachowiak)).
pos(f(bcac,abbb)).
pos(f(bacc,acarolflorence)).
pos(f(ccbc,aaab)).
pos(f(awayneknight,aleilanisarelle)).
pos(f(afrancomirabella,amarcospicuglia)).
pos(f(aaca,agiancarloscuderi)).
pos(f(aangelinasarova,astefanpetrov)).
pos(f(akronthalerthomas,amaxmller)).
pos(f(ahughkeaysbyrne,asharonstone)).
pos(f(afrankcturner,cbab)).
pos(f(bbbb,agretascacchi)).
pos(f(aabb,asheilapaterson)).
pos(f(asharonstone,amichaeldouglas)).
pos(f(abba,adillonmoen)).
pos(f(amarksangster,aheathcotewilliams)).
pos(f(ageorgeclooney,aannejacques)).
pos(f(abillyconnolly,bbca)).
pos(f(caaa,adavidarnett)).
pos(f(alaurabetti,astefanodionisi)).
pos(f(aleilanisarelle,ajackmcgee)).
pos(f(aalicjajachiewicz,ajannowicki)).
pos(f(amarkgantt,abradpitt)).
pos(f(aluciasardo,amaurizionicolosi)).
pos(f(achelcieross,adenisarndt)).
pos(f(ajurneesmollett,cbcc)).
pos(f(abbb,acesareapolito)).
pos(f(acarolflorence,acbb)).
pos(f(ajuliaroberts,adinaconnolly)).
pos(f(aianholm,acca)).
pos(f(aedkross,adinaconnolly)).
pos(f(abenjohnson,asheilapaterson)).
pos(f(acatherinezetajones,ascottcaan)).
pos(f(aelliottgould,acbb)).
pos(f(cbcc,abba)).
pos(f(aleahayres,adeanstockwell)).
pos(f(aberniemac,abradpitt)).
pos(f(bbca,adannflorek)).
pos(f(aangelahall,avincentdonofrio)).
pos(f(aginachiarelli,agilbellows)).
pos(f(arobyndouglass,amarccaleb)).
pos(f(aserenaautieri,acarmelogalati)).
pos(f(asciveresmarianna,abiagiobarone)).
pos(f(amarcospicuglia,afrancomirabella)).
pos(f(amarksangster,aaba)).
pos(f(avolkerranisch,aclaudiamessner)).
pos(f(abbc,apieradegliesposti)).
pos(f(aangelahall,aaaa)).
pos(f(aantonradichev,anevenakokanova)).
pos(f(acoralyzahonero,bcbc)).
pos(f(aabc,abcb)).
pos(f(apaolaciampi,astefanodionisi)).
pos(f(bacc,aeddiejemison)).
pos(f(aangelahall,alylelovett)).
pos(f(ageorgistamatov,amariashopova)).
pos(f(asummereric,astevekalfa)).
pos(f(aaltmanroberti,apetergallagher)).
pos(f(arobertculp,cabb)).
pos(f(acatherinezetajones,ageorgeclooney)).
pos(f(aaaa,aleahayres)).
pos(f(aarmelledeutsch,aguillaumeromain)).
pos(f(aluciasardo,aconsuelolupo)).
pos(f(apaullnolan,ageorgeclooney)).
pos(f(aauroraquattrocchi,bcac)).
pos(f(avergnejeanpierre,apatricejuiff)).
pos(f(bcab,alorigalinski)).
pos(f(asoderberghsteven,adontiffany)).
pos(f(aivandimov,avyarakovacheva)).
pos(f(ajorgerhernandez,ageorgeclooney)).
pos(f(adinamerrill,adeanstockwell)).
pos(f(apatricejuiff,abrnicebejo)).
pos(f(acarmelogalati,abarbaratabita)).
pos(f(aalicjajachiewicz,aemilmarkov)).
pos(f(aaac,cabc)).
pos(f(abaa,aceceliaannbirt)).
pos(f(aianholm,cccc)).
pos(f(cbca,astefanodionisi)).
pos(f(baca,aludwigbriand)).
pos(f(agrimaldiaurelioi,bbba)).
pos(f(acbc,aauroraquattrocchi)).
pos(f(astephentobolowsky,ajeannetripplehorn)).
pos(f(adillonmoen,acca)).
pos(f(amarcoleonardi,alaurabetti)).
pos(f(anevenakokanova,abogomilsimeonov)).
pos(f(aaba,ajanchappell)).
pos(f(afloramontgomery,aheathcotewilliams)).
pos(f(acac,accc)).
pos(f(adontiffany,aminianden)).
pos(f(abac,ageorgistamatov)).
pos(f(asamantharnier,abcb)).
pos(f(abac,aacc)).
pos(f(babb,amarksangster)).
pos(f(aleilanisarelle,awayneknight)).
pos(f(acesareapolito,abbb)).
pos(f(accc,asciveresmarianna)).
pos(f(agutjahrrainer,atommikulla)).
pos(f(averhoevenpauli,adenisarndt)).
pos(f(aabb,ajurneesmollett)).
pos(f(ahughdancy,acharlotterampling)).
pos(f(ajuttawachowiak,adietermann)).
pos(f(aneilmaskell,amarksangster)).
pos(f(athomasstielner,akarinthaler)).
pos(f(anormanarmour,bbca)).
pos(f(aradarassimov,alucavitrano)).
pos(f(bcbc,agabriellelazure)).
pos(f(ccba,abrigittefossey)).
pos(f(akinkelmartin,baac)).
pos(f(bbab,aantoniettacarbonetti)).
pos(f(bccc,aapprederisfranck)).
pos(f(acbb,aceceliaannbirt)).
pos(f(aivanbratanov,amariashopova)).
pos(f(apaolaciampi,babc)).
pos(f(aantoniettacarbonetti,agiancarloscuderi)).
pos(f(bcaa,alloydalan)).
pos(f(agiancarloscuderi,aaca)).
pos(f(aarmelledeutsch,ccba)).
pos(f(adeanstockwell,aleahayres)).
pos(f(agesinecukrowski,adietermann)).
pos(f(ajuliedray,bbaa)).
pos(f(aantoninobruschetta,atizianalodato)).
pos(f(abaa,alorigalinski)).
pos(f(aberniemac,bcab)).
pos(f(aluciacammalleri,accc)).
pos(f(aantoninobruschetta,agabrieleferzetti)).
pos(f(aloccorbery,baca)).
pos(f(ageorgeclooney,atimothypaulperez)).
pos(f(aberniemac,bacc)).
pos(f(aleilanisarelle,cbba)).
pos(f(aeddasabatini,bcac)).
pos(f(aludwigbriand,abrnicebejo)).
pos(f(aberniemac,acaseyaffleck)).
pos(f(acatherinezetajones,aandygarcia)).
pos(f(aradarassimov,aaab)).
pos(f(acca,aconnorwiddows)).
pos(f(acatonjonesmichael,aindiravarma)).
pos(f(adillonmoen,ajurneesmollett)).
pos(f(aginachiarelli,aabb)).
pos(f(arenateschroeter,aleonardlansink)).
pos(f(akrgnther,ahorstkummeth)).
pos(f(alaurabetti,babc)).
pos(f(asalvatorelazzaro,apieradegliesposti)).
pos(f(afloramontgomery,adavidmorrissey)).
pos(f(ahumecronyn,cabb)).
pos(f(acatherinezetajones,aedkross)).
pos(f(avolkerranisch,ccac)).
pos(f(abca,abba)).
pos(f(amarenschumacher,baac)).
pos(f(asheilapaterson,adannflorek)).
pos(f(abrnicebejo,bccc)).
pos(f(aaca,amaurolenares)).
pos(f(agusmercurio,adebraengle)).
pos(f(cccb,abattiatofranco)).
pos(f(aestefanacastro,apatricejuiff)).
pos(f(aabc,apierrearditi)).
pos(f(aalicjajachiewicz,alyubomirbachvarov)).
pos(f(cacb,adinaconnolly)).
pos(f(apetyasilyanova,astefandanailov)).
pos(f(abca,aginachiarelli)).
pos(f(abab,babc)).
pos(f(abrigittefossey,aludwigbriand)).
pos(f(astancollymore,atimberrington)).
pos(f(caaa,ahughkeaysbyrne)).
pos(f(aluciasardo,amanliosgalambro)).
pos(f(ccca,caca)).
pos(f(anelsonpeltz,adinaconnolly)).
pos(f(aceceliaannbirt,ageorgeclooney)).
pos(f(aacc,amariashopova)).
pos(f(acatherinezetajones,acaseyaffleck)).
pos(f(aannejacques,anelsonpeltz)).
pos(f(aivandimov,akunkabaeva)).
pos(f(ahughdancy,asharonstone)).
pos(f(adorothymalone,abillcable)).
pos(f(cccb,ccbc)).
pos(f(abiagiobarone,aluciacammalleri)).
pos(f(adinamerrill,arichardegrant)).
pos(f(bccc,baca)).
pos(f(aguillaumeromain,aabc)).
pos(f(aaca,afabiolobello)).
pos(f(amarkgantt,bcab)).
pos(f(amariashopova,anikoladadov)).
pos(f(abrigittefossey,aguillaumeromain)).
pos(f(anicolegrimaudo,cccb)).
pos(f(atimrobbins,aleahayres)).
pos(f(abrnicebejo,abcb)).
pos(f(ageorgeclooney,aelliottgould)).
pos(f(afredward,aleahayres)).
pos(f(asharonstone,cbba)).
pos(f(cbcb,asurchadzhievstefani)).
pos(f(adietermann,agesinecukrowski)).
pos(f(acab,amikhailmikhajlov)).
pos(f(amaxmller,amarisaburger)).
pos(f(ageorgistamatov,avyarakovacheva)).
pos(f(aminianden,ageorgeclooney)).
pos(f(apetyasilyanova,adimitarhadzhiyanev)).
pos(f(apetardespotov,apetyasilyanova)).
pos(f(ajamessikking,cabb)).
pos(f(ascottcaan,apaullnolan)).
pos(f(abrnicebejo,apierrearditi)).
pos(f(avannifois,abarbaratabita)).
pos(f(bbac,aalicjajachiewicz)).
pos(f(ajustinmonjo,cbbb)).
pos(f(acaseyaffleck,acarolflorence)).
pos(f(apatricejuiff,aalexandrawinisky)).
pos(f(babc,abab)).
pos(f(averhoevenpauli,abillcable)).
pos(f(aaltmanroberti,atimrobbins)).
pos(f(asummereric,bcbc)).
pos(f(ageorgedzundza,asharonstone)).
pos(f(apieradegliesposti,afabiolobello)).
pos(f(acorradofortuna,aluciasardo)).
pos(f(asciveresmarianna,accc)).
pos(f(afrankcturner,bbca)).
pos(f(abillyconnolly,abba)).
pos(f(abenjaminmouton,achelcieross)).
pos(f(aacc,aangelinasarova)).
pos(f(abaa,amarkgantt)).
pos(f(ajackmcgee,aleilanisarelle)).
pos(f(cbab,abenjohnson)).
pos(f(ccca,aberniemac)).
pos(f(cccb,aluciasardo)).
pos(f(ajanchappell,astancollymore)).
pos(f(adavidmorrissey,afloramontgomery)).
pos(f(aceceliaannbirt,bacc)).
pos(f(aangelinasarova,anikoladadov)).
pos(f(aemiliaradeva,apetardespotov)).
pos(f(agilbellows,bbca)).
pos(f(aangelinasarova,aivandimov)).
pos(f(aivandimov,amariashopova)).
pos(f(abradpitt,acarolflorence)).
pos(f(aantoninobruschetta,adonatellafinocchiaro)).
pos(f(acatherinezetajones,adontiffany)).
pos(f(babc,alaurabetti)).
pos(f(atraykovatanas,astefandanailov)).
pos(f(adidierdijoux,abrnicebejo)).
pos(f(caab,agretascacchi)).
pos(f(akarinthaler,atommikulla)).
pos(f(abaa,ajorgerhernandez)).
pos(f(acatonjonesmichael,astancollymore)).
pos(f(abruceayoung,asharonstone)).
pos(f(amarkusbker,cbaa)).
pos(f(aheathcotewilliams,ajanchappell)).
pos(f(caab,aangelahall)).
pos(f(atheresascholze,bccb)).
pos(f(aangelinasarova,aviktordanchenko)).
pos(f(avincentdonofrio,aangelahall)).
pos(f(aleilanisarelle,abenjaminmouton)).
pos(f(aaaa,agretascacchi)).
pos(f(bcac,apaolaciampi)).
pos(f(aluciasardo,aenzodimartino)).
pos(f(adinaconnolly,acaseyaffleck)).
pos(f(aelliottgould,bacc)).
pos(f(cabc,ascottcaan)).
pos(f(adenisarndt,achelcieross)).
pos(f(aaltmanroberti,arichardegrant)).
pos(f(ageorgeclooney,alorigalinski)).
pos(f(alyubomirbobchevski,aangelinasarova)).
pos(f(avergnejeanpierre,adidierdijoux)).
pos(f(ametcalfestephen,abenjohnson)).
pos(f(bcaa,adavidarnett)).
pos(f(alyubomirkanev,anevenakokanova)).
pos(f(akirilyanev,acab)).
pos(f(acatherinezetajones,alarrysontag)).
pos(f(afloramontgomery,aterenceharvey)).
pos(f(caca,abaa)).
pos(f(atimberrington,adavidmorrissey)).
pos(f(arenateschroeter,adietermann)).
pos(f(adavidarnett,cbbb)).
pos(f(adinaconnolly,aaac)).
pos(f(cabc,aedkross)).
pos(f(abattiatofranco,acorradofortuna)).
pos(f(aellenthomas,aneilmaskell)).
pos(f(ccbb,agerdlohmeyer)).
pos(f(acaseyaffleck,alorigalinski)).
pos(f(apenlopecruz,baaa)).
pos(f(caca,bcab)).
pos(f(amarksangster,astancollymore)).
pos(f(aeddasabatini,adanielegalea)).
pos(f(asharonstone,alewissmith)).
pos(f(caba,ajuliedray)).
pos(f(adorothymalone,awayneknight)).
pos(f(aberniemac,abaa)).
pos(f(asoderberghsteven,aaac)).
pos(f(atzvetolyubrakovski,abac)).
pos(f(anicolegrimaudo,alucavitrano)).
pos(f(aellenthomas,adavidmorrissey)).
pos(f(cbcb,ccaa)).
pos(f(bcaa,ahughkeaysbyrne)).
pos(f(bcbc,atonetticlaudio)).
pos(f(aludwigbriand,asamantharnier)).
pos(f(caab,aleahayres)).
pos(f(cbbc,afloramontgomery)).
pos(f(adietermann,arenateschroeter)).
pos(f(abradpitt,aeddiejemison)).
pos(f(amiguelferrer,asharonstone)).
pos(f(ahughdancy,aellenthomas)).
pos(f(aaba,afloramontgomery)).
pos(f(aalexandrawinisky,bccc)).
pos(f(amiguelferrer,caaa)).
pos(f(baac,ccbb)).
pos(f(ageorgeclooney,caca)).
pos(f(avannifois,baab)).
pos(f(bcba,ajeannetripplehorn)).
pos(f(bbcb,akunkabaeva)).
pos(f(caac,aluciasardo)).
pos(f(afabiolobello,aantoniettacarbonetti)).
pos(f(adebraengle,astevekuhn)).
pos(f(acarolflorence,bcab)).
pos(f(asharonstone,abillyconnolly)).
pos(f(abenjaminmouton,ajeannetripplehorn)).
pos(f(amarkusbker,akarinthaler)).
pos(f(aemiliaradeva,astoychomazgalov)).
pos(f(cabb,adenzelwashington)).
pos(f(abrnicebejo,aloccorbery)).
pos(f(apatricejuiff,ajuliedray)).
pos(f(aannejacques,adavidsontag)).
pos(f(astefanpejchev,aangelinasarova)).
pos(f(asamantharnier,bbaa)).
pos(f(bccc,abrnicebejo)).
pos(f(baaa,aeddasabatini)).
pos(f(ajuttawachowiak,aandreasschwaiger)).
pos(f(aganchoganchev,akunkabaeva)).
pos(f(apunchevborislav,alyubomirkanev)).
pos(f(ajeannetripplehorn,ajackmcgee)).
pos(f(apierrearditi,asamantharnier)).
pos(f(anevenakokanova,alyubomirkanev)).
pos(f(apaullnolan,bacc)).
pos(f(amarcoleonardi,aauroraquattrocchi)).
pos(f(akostatsonev,aalicjajachiewicz)).
pos(f(cbac,alyubomirkanev)).
pos(f(ccca,acarolflorence)).
pos(f(apierrearditi,abrigittefossey)).
pos(f(accc,bacb)).
pos(f(acba,baaa)).
pos(f(atimrobbins,aangelahall)).
pos(f(asydneypollack,adinamerrill)).
pos(f(aangelinasarova,astefanpejchev)).
pos(f(ageorgedzundza,achelcieross)).
pos(f(aeddiejemison,abaa)).
pos(f(aalexandrawinisky,caba)).
pos(f(abac,astefanpetrov)).
pos(f(acharlotterampling,babb)).
pos(f(bbba,aauroraquattrocchi)).
pos(f(abonnetchristiani,astevekalfa)).
pos(f(acesareapolito,abab)).
pos(f(arenateschroeter,ajrggudzuhn)).
pos(f(abillyconnolly,aginachiarelli)).
pos(f(adavidsontag,cabc)).
pos(f(arenateschroeter,aandreasschwaiger)).
pos(f(agrimaldiaurelioi,astefanodionisi)).
pos(f(astefanodionisi,aeddasabatini)).
pos(f(adavidsontag,acatherinezetajones)).
pos(f(acesareapolito,acba)).
pos(f(asharonstone,abca)).
pos(f(astancollymore,ajanchappell)).
pos(f(awhoopigoldberg,avincentdonofrio)).
pos(f(aeddasabatini,acbc)).
pos(f(aginachiarelli,abca)).
pos(f(aviktordanchenko,aangelinasarova)).
pos(f(acbb,aberniemac)).
pos(f(agrimaldiaurelioi,baaa)).
pos(f(afabiolobello,aaca)).
pos(f(aivantonev,avyarakovacheva)).
pos(f(avincenzocrivello,aaca)).
pos(f(amanliosgalambro,aradarassimov)).
pos(f(agilbellows,cbab)).
pos(f(adinaconnolly,abradpitt)).
pos(f(bcca,aaca)).
pos(f(bcac,alaurabetti)).
pos(f(bccc,avergnejeanpierre)).
pos(f(aenzodimartino,aaca)).
pos(f(agabrieleferzetti,aaab)).
pos(f(ajuliedray,abcb)).
pos(f(atimberrington,adavidthewlis)).
pos(f(aginachiarelli,aconnorwiddows)).
pos(f(arichardegrant,agretascacchi)).
pos(f(astoychomazgalov,ccaa)).
pos(f(aantoniettacarbonetti,asalvatorelazzaro)).
pos(f(agabrieleferzetti,acorradofortuna)).
pos(f(acatonjonesmichael,ahughdancy)).
pos(f(bccb,astephanbernhard)).
pos(f(ascottcaan,afrankpatton)).
pos(f(bcbc,acoralyzahonero)).
pos(f(acorradofortuna,agabrieleferzetti)).
pos(f(alylelovett,adinamerrill)).
pos(f(aclaudiamessner,aandreasschwaiger)).
pos(f(abcb,asamantharnier)).
pos(f(baac,amarenschumacher)).
pos(f(aannamariagherardi,acorradofortuna)).
pos(f(astefanodionisi,alaurabetti)).
pos(f(ametcalfestephen,aconnorwiddows)).
pos(f(abiagiobarone,aserenaautieri)).
pos(f(asurchadzhievstefani,atzenokandov)).
pos(f(ajeannetripplehorn,abruceayoung)).
pos(f(alyubomirbachvarov,cbac)).
pos(f(abrionjames,aleahayres)).
pos(f(accc,aserenaautieri)).
pos(f(caba,abrigittefossey)).
pos(f(ajeannetripplehorn,cbba)).
pos(f(avincentdonofrio,agretascacchi)).
pos(f(asamantharnier,aludwigbriand)).
pos(f(acca,ajaimzwoolvett)).
pos(f(aauroraquattrocchi,babc)).
pos(f(abab,bbba)).
pos(f(cabb,arobertculp)).
pos(f(ajrggudzuhn,ajuttawachowiak)).
pos(f(abac,aivanbratanov)).
pos(f(akinkelmartin,athomasstielner)).
pos(f(amarccaleb,caaa)).
pos(f(cabc,ajuliaroberts)).
pos(f(avergnejeanpierre,avincentlecoeur)).
pos(f(acatherinezetajones,cacb)).
pos(f(amikhailmikhajlov,ccaa)).
pos(f(agerdlohmeyer,amarenschumacher)).
pos(f(astefandanailov,asonyadjulgerova)).
pos(f(ahorstkummeth,amarenschumacher)).
pos(f(alylelovett,acynthiastevenson)).
pos(f(abbc,afrancomirabella)).
pos(f(aalexandrawinisky,avincentlecoeur)).
pos(f(acba,acesareapolito)).
pos(f(astevekalfa,acoralyzahonero)).
pos(f(aannejacques,ascottcaan)).
pos(f(acynthiastevenson,aaaa)).
pos(f(apenlopecruz,amarcoleonardi)).
pos(f(aivangrigorov,anevenakokanova)).
pos(f(bacb,abiagiobarone)).
pos(f(ageorgistamatov,abac)).
pos(f(amarinovichanton,astefanpetrov)).
pos(f(adeanstockwell,aangelahall)).
pos(f(achelcieross,bcba)).
pos(f(agrimaldiaurelioi,caac)).
pos(f(amarenschumacher,amaxmller)).
pos(f(ajorgerhernandez,bacc)).
pos(f(bccb,ccac)).
pos(f(ajuliedray,apatricejuiff)).
pos(f(ageorgeclooney,aceceliaannbirt)).
pos(f(bcca,apieradegliesposti)).
pos(f(amarisaburger,atommikulla)).
pos(f(araffaeladavi,acesareapolito)).
pos(f(anelsonpeltz,acatherinezetajones)).
pos(f(amichalbajor,cbac)).
pos(f(atizianalodato,aaab)).
pos(f(ajannowicki,anevenakokanova)).
pos(f(astevekalfa,afranoisechristophe)).
pos(f(aradarassimov,amanliosgalambro)).
pos(f(aradarassimov,acorradofortuna)).
pos(f(bbbc,astevekalfa)).
pos(f(ajurneesmollett,adillonmoen)).
pos(f(amarkusbker,amarenschumacher)).
pos(f(acesareapolito,apenlopecruz)).
pos(f(afrankpatton,abaa)).
pos(f(alorigalinski,bacc)).
pos(f(adavidsontag,adinaconnolly)).
pos(f(aludwigbriand,aabc)).
pos(f(amikhailmikhajlov,aangelinasarova)).
pos(f(agabrieleferzetti,alucavitrano)).
pos(f(atimothypaulperez,ascottcaan)).
pos(f(cbab,anormanarmour)).
pos(f(ajeannetripplehorn,abenjaminmouton)).
pos(f(caaa,ajustinmonjo)).
pos(f(ccaa,atzenokandov)).
pos(f(acaseyaffleck,cabc)).
pos(f(akirilyanev,aangelinasarova)).
pos(f(akunkabaeva,aacc)).
pos(f(amariashopova,aivandimov)).
pos(f(awhoopigoldberg,asydneypollack)).
pos(f(adorothymalone,astephentobolowsky)).
pos(f(cacb,acatherinezetajones)).
pos(f(aminianden,aandygarcia)).
pos(f(astefanodionisi,apaolaciampi)).
pos(f(acharlotterampling,aaba)).
pos(f(aminianden,alarrysontag)).
pos(f(arobyndouglass,astevekuhn)).
pos(f(ccba,ajuliedray)).
pos(f(acatonjonesmichael,babb)).
pos(f(ascottcaan,ajorgerhernandez)).
pos(f(awayneknight,adorothymalone)).
pos(f(aloccorbery,ajuliedray)).
pos(f(aginachiarelli,abillyconnolly)).
pos(f(adinamerrill,caab)).
pos(f(aemiliaradeva,aivangrigorov)).
pos(f(apetergallagher,aangelahall)).
pos(f(cbab,cbcc)).
pos(f(ajannowicki,aalicjajachiewicz)).
pos(f(aemiliaradeva,akostatsonev)).
pos(f(agutjahrrainer,ahorstkummeth)).
pos(f(agabrieleferzetti,aantoninobruschetta)).
pos(f(cabb,ajuliaroberts)).
pos(f(adinamerrill,bbbb)).
pos(f(cabc,aandygarcia)).
pos(f(baca,bccc)).
pos(f(aeddasabatini,baaa)).
pos(f(aangelahall,adeanstockwell)).
pos(f(asurchadzhievstefani,alyubomirbobchevski)).
pos(f(agilbellows,cccc)).
pos(f(abbc,aantoniettacarbonetti)).
pos(f(avincenzocrivello,aluciasardo)).
pos(f(aganchoganchev,avyarakovacheva)).
pos(f(atimothypaulperez,bacc)).
pos(f(adidierdijoux,asamantharnier)).
pos(f(cacb,cabc)).
pos(f(asheilapaterson,ajaimzwoolvett)).
pos(f(bccc,ajuliedray)).
pos(f(ccac,aandreasschwaiger)).
pos(f(bccc,aarmelledeutsch)).
pos(f(afrankcturner,acca)).
pos(f(asharonstone,abruceayoung)).
pos(f(cbca,acbc)).
pos(f(aloccorbery,aestefanacastro)).
pos(f(aacb,avincenzocrivello)).
pos(f(alaurabetti,bbba)).
pos(f(amichalbajor,anevenakokanova)).
pos(f(achelcieross,abenjaminmouton)).
pos(f(aclaudiamessner,aleonardlansink)).
pos(f(arobyndouglass,amiguelferrer)).
pos(f(avincenzocrivello,apieradegliesposti)).
pos(f(aloccorbery,abrnicebejo)).
pos(f(aleahayres,arichardegrant)).
pos(f(acab,atzenokandov)).
pos(f(aalicjajachiewicz,astoychomazgalov)).
pos(f(aalexandrawinisky,apierrearditi)).
pos(f(aloccorbery,asamantharnier)).
pos(f(adinaconnolly,adontiffany)).
pos(f(adimitarhadzhiyanev,anevenakokanova)).
pos(f(arobyndouglass,agusmercurio)).
pos(f(acac,aconsuelolupo)).
pos(f(acatonjonesmichael,aneilmaskell)).
pos(f(asurchadzhievstefani,akirilyanev)).
pos(f(cbba,adorothymalone)).
pos(f(bbba,agrimaldiaurelioi)).
pos(f(astefandanailov,aemiliaradeva)).
pos(f(aengelhardtwilhelm,baac)).
pos(f(baca,adidierdijoux)).
pos(f(avincentlecoeur,baca)).
pos(f(ajanchappell,aaba)).
pos(f(cbac,aantonradichev)).
pos(f(acynthiastevenson,asydneypollack)).
pos(f(asavahashamov,acab)).
pos(f(aabc,adidierdijoux)).
pos(f(averhoevenpauli,awayneknight)).
pos(f(aeddiejemison,bcab)).
pos(f(amarccaleb,arobyndouglass)).
pos(f(astevekalfa,afirminerichard)).
pos(f(acbb,aeddiejemison)).
pos(f(cccb,anicolegrimaudo)).
pos(f(bcaa,agusmercurio)).
pos(f(bbcb,aangelinasarova)).
pos(f(adannflorek,ajurneesmollett)).
pos(f(ahughdancy,amarksangster)).
pos(f(bbca,abca)).
pos(f(aminianden,ajuliaroberts)).
pos(f(caab,acynthiastevenson)).
pos(f(aauroraquattrocchi,bbba)).
pos(f(adenzelwashington,cabb)).
pos(f(abraunbettinai,baac)).
pos(f(acca,aianholm)).
pos(f(acaseyaffleck,ajorgerhernandez)).
pos(f(adinamerrill,asydneypollack)).
pos(f(anevenakokanova,apetardespotov)).
pos(f(cbcc,asharonstone)).
pos(f(bacc,apaullnolan)).
pos(f(acatherinezetajones,ajuliaroberts)).
pos(f(ccca,aeddiejemison)).
pos(f(atimberrington,astancollymore)).
pos(f(bbba,apaolaciampi)).
pos(f(alarrysontag,acatherinezetajones)).
pos(f(aaac,aannejacques)).
pos(f(amanliosgalambro,agabrieleferzetti)).
pos(f(aminianden,adontiffany)).
pos(f(aabc,aludwigbriand)).
pos(f(cccc,adannflorek)).
pos(f(amichalbajor,aalicjajachiewicz)).
pos(f(bccc,asamantharnier)).
pos(f(aantoniettacarbonetti,bbab)).
pos(f(cabb,awilliamatherton)).
pos(f(aangelinasarova,aivankondov)).
pos(f(abogomilsimeonov,aalicjajachiewicz)).
pos(f(aceceliaannbirt,ascottcaan)).
pos(f(acarmelogalati,acac)).
pos(f(avannifois,aluciacammalleri)).
pos(f(ajaimzwoolvett,bbca)).
pos(f(cabc,adavidsontag)).
pos(f(alucavitrano,ccbc)).
pos(f(afrankcturner,ajurneesmollett)).
